### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [faruktoptas/FancyShowCaseView#100]
Hello...

Your project is Amazing... I came across it and I want to help contribute to your project by using my Logo Design Skills to contribute and help create a LOGO/ICON for your project...

I am designing an idea concept already... You can also give your own idea for me to create...

I will update what I have done here so you can give me your feedback or possibly any change or tweak you may want... also your prefered colour choice.

Regards.

**Comment by faruktoptas** [comment]
Thanks so much @chimzycash 

I am looking forward to see your idea concept. Feel free to use any color. You can check material color palettes.

**Comment by chimzycash** [comment]
Hello...

Here are my design ideas...

![logo design_fancy showcase_presentation](https://user-images.githubusercontent.com/37814297/40502368-a85022f0-5f82-11e8-94c2-aa615e56c55d.jpg)


![logo design_fancy showcase_presentation 2](https://user-images.githubusercontent.com/37814297/40502383-b20029c6-5f82-11e8-98ea-2e379a6dd6fe.jpg)


![logo design_fancy showcase_thumbnail icons](https://user-images.githubusercontent.com/37814297/40502391-b9152ff4-5f82-11e8-8f8f-66cd61ad9a85.jpg)



![logo design_fancy showcase_idea concept](https://user-images.githubusercontent.com/37814297/40502405-c02a788a-5f82-11e8-8e54-a8f07621f5c1.jpg)

**Comment by chimzycash** [comment]
@faruktoptas 

You can also share your own design concept if you have for me to create...

**Comment by faruktoptas** [comment]
@chimzycash 
I appreciate for your beautiful designs :)
I like the latest one.

![40511214-f1318f9a-5f96-11e8-9666-f52054b17ad0](https://user-images.githubusercontent.com/1595227/40590481-25f4d7c8-6208-11e8-8b9b-98e58fba4565.jpg)

I've created a color palette for my sample app:
[https://www.materialpalette.com/deep-orange/cyan](https://www.materialpalette.com/deep-orange/cyan)

What do you think about the palette? If it's ok can you change to color to deep-orange and share with me?

**Comment by chimzycash** [comment]
@faruktoptas 

i'm glad you liked one of the design concepts... :)

OK... i will change the background to the deep-orange color and share

**Comment by faruktoptas** [comment]
Thank you @chimzycash 
I will use this color palette and logo in the sample app soon :)

**Comment by chimzycash** [comment]
That's great @faruktoptas 

I will prepare all the files including the vector files and icons for you to use and update here on your project...

**Comment by chimzycash** [comment]
@faruktoptas ...Thank you for merging the logo design to your project... It showed that my contribution was of value to you... Here is the google drive link for the VECTOR FILES for future use...

https://drive.google.com/drive/folders/1Wu_9N4ptw-W2nortGSyHBnWh-h6qlyx1?usp=sharing
