### ISSUE TITLE
Dismiss without trigger ondismiss

### ISSUE THREAD

**Issue by Verdurakh** [faruktoptas/FancyShowCaseView#106]
So a scenario I'm having is that on screen load I show a FancyBox with some information and when it is dismissed the screen progresses with a call to a method.

The problem arises for example when the user press the back button then I want to close the fancybox without triggering the method since that context would no longer be available when the animation finishes.

Now I have to accomplish this by adding a flag that decides if the method should trigger or not and setting that in the onBackPressed method.

What I would propose is adding a method like public void hide(boolean skipMethod) or the like, or any other way of skipping the method call?

**Comment by azizur-rehman** [comment]
I am also waiting for this issue to be solved....

**Comment by faruktoptas** [comment]
Sorry for the late response. I'll fix it asap.

**Comment by faruktoptas** [comment]
Getter/setter methods for dismissListener are protected now. It should have been public. I will make it public with the next release. So when you press the back button you need to set `dismissListener` to `null` then call `hide()` method. This will fix your problem.

**Comment by Verdurakh** [comment]
Awesome! Yeah that will solve the issue :)

Also opens up the ability to change the event which can be useful in some cases

**Comment by faruktoptas** [comment]
@Verdurakh 
Here is the new release https://github.com/faruktoptas/FancyShowCaseView/releases/tag/1.0.1

**Comment by Verdurakh** [comment]
thanks for that, it will be super useful! 👍
