### ISSUE TITLE
FancyShowCaseView not focus view in a fragment in viewpager

### ISSUE THREAD

**Issue by munishkumar071** [faruktoptas/FancyShowCaseView#107]
In a viewPager i created two objects of FancyShowCaseView and add in a queue.
if i call the method in on createView the its working fine but in setUserVisibleHint() method it gives an Issue
Issue is first fancy showcase view not focus the view

![untitled](https://user-images.githubusercontent.com/40294705/41464231-3a8743b6-70b7-11e8-9c7f-5df689dd3db3.png)

and 2nd view working fine

![untitled](https://user-images.githubusercontent.com/40294705/41464281-61721d34-70b7-11e8-9e39-e6d67861c7f7.png)

**Comment by faruktoptas** [comment]
Can you share the code that you are creating FancyShowCaseView() instance and call show() method?
If the view is null or not inflated yet, it can't focus.

**Comment by faruktoptas** [comment]
@munishkumar071 
You must call it after view creation. Because focus needs view position and size. So please use it in `onCreateView()` method.

**Comment by NateshR** [comment]
this is still now working. I am calling it in `onViewCreated`, whole screen is getting focused, not on single view.

**Comment by faruktoptas** [comment]
@NateshR view should be inflated when you call `show` method otherwise view width/height values will be 0. If you share the code snippet to show your implementation I can see the problem.

**Comment by divyancod** [comment]
It is not working when the activity is resumed. When we switch app the showcase items are not clickable.

**Comment by faruktoptas** [comment]
@divyancod can you share more details please? 
- Your implementation
- layout xml file
- Screenshots
