### ISSUE TITLE
How to dismiss only in TouchOnFocusedView not on body?

### ISSUE THREAD

**Issue by iman2420** [faruktoptas/FancyShowCaseView#108]
How to dismiss **showCase** only in **TouchOnFocusedView** not on body?

**Comment by faruktoptas** [comment]
@iman2420 it is possible with `enableTouchOnFocusedView(true)` . There is an example [here](https://github.com/faruktoptas/FancyShowCaseView/blob/09955b994b89884149790669320dcfcf4c5bb900/app/src/main/java/me/toptas/fancyshowcasesample/MainActivity.java#L93)

**Comment by clockworkant** [comment]
This doesn't work. The showcase view isn't dismissing when the focus view is pressed.

**Comment by faruktoptas** [comment]
If you enable touching on focused view the showcase doesn't dismiss. If you want to dismiss it you have to call `FancyCaseView.hideCurrent(this)` method.

**Comment by clockworkant** [comment]
Hi @faruktoptas, please forgive my flippant comment earlier. I appreciate you replying.

I'd like to be able to hide the fancy view without changing the implementation of the `FocusView`. I think you are suggesting that I modify the `FocusView` onClickListener behaviour to call `FancyCaseView.hideCurrent(this)`. I'd rather not do this as I want to keep a separation of concerns.

I've looked at the android api and there isn't a way to `get` the `onClickListener` of a view. I had thought to get the listener and wrap it with an adapter that called both `hideCurrent` and the original click behaviour.

so the original issue kind of still exists. How can I call the `hideCurrent` without modifying the original view onClickListener?

If it's not possible, that's ok!
