### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by faruktoptas** [faruktoptas/FancyShowCaseView#11]
- Explain all Builder parameters in README.md
- Add more examples with screenshots

**Comment by goanpixie** [comment]
Hi..I want to work on the issue! I am first time contributor and would appreciate a little help starting up.

**Comment by faruktoptas** [comment]
Thank you :) 
You can start from explaining all Builder methods in readme.md

**Comment by faruktoptas** [comment]
Let me know if you need help.

**Comment by harshvardhan-takawale** [comment]
I too am a first timer. Please do tell me if I can help in any way.

**Comment by chandlerbaggett** [comment]
Hello, it appears that this is still open... I'll take a stab at it if it's still available!

**Comment by faruktoptas** [comment]
@chandlerbaggett there is a pr for this issue #58  But this is not enough. Each builder param should be explained with examples. Maybe adding a wiki would be better.

**Comment by faruktoptas** [comment]
Wiki includes all builder parameters and more examples. This issue is no longer required.
