### ISSUE TITLE
No focus on fab

### ISSUE THREAD

**Issue by Micpol** [faruktoptas/FancyShowCaseView#110]
It happens only after reenabling tutorial and only in a fragment kept in memory(it's scanning for bluetooth devices) and when I move from any othe fragment to this one, while tutorial is enabled. However it won't happen if you close the app. 
I tried .fitSystemWindows(true) and it doesn't work. I tried debugging focus location, but got NPE. I use showcaseView in onViewCreated method. For both situations I use the same method, fab is working properly in both situations. 

Screen:

![36890901_2238977152806178_6431817781796143104_n](https://user-images.githubusercontent.com/19592202/42474610-6302be78-83c8-11e8-933b-3154bb554c98.jpg)
 
Focus working:

![36914101_2239003319470228_3795403440595664896_n](https://user-images.githubusercontent.com/19592202/42474647-89ea4d8a-83c8-11e8-9db7-d16842ad8bdc.jpg)

**Comment by faruktoptas** [comment]
Hi @Micpol 
Can you share the code how you build FancyShowCaseView? In which method of fragment/activity

**Comment by Micpol** [comment]
Hm.. it seems like the problem is gone, even though I haven't change anything in this fragment. I was trying to reproduce this bug again, but failed to. Now everything is working as intended, sorry for bothering you and thanks for a fast answer.

**Comment by Micpol** [comment]
Hm.. it seems like the problem is gone, even though I haven't change anything in this fragment. I was trying to reproduce this bug again, but failed to. Now everything is working as intended, sorry for bothering you and thanks for a fast answer.
