### ISSUE TITLE
Wrong focus on Android 4.4

### ISSUE THREAD

**Issue by axionnneeeel** [faruktoptas/FancyShowCaseView#111]
Hello, everything is working fine on newer phones but for Android 4.4 isn't focusing right. Any solutions ?

**Comment by axionnneeeel** [comment]
anyone ?

**Comment by faruktoptas** [comment]
@axionnneeeel 
Can you share  a screenshot, your layout xml and code to fire FancyShowCaseView?

**Comment by faruktoptas** [comment]
Sample project works fine with 4.4 devices. There was a problem for full-screen activities. It is fixed with https://github.com/faruktoptas/FancyShowCaseView/commit/b6a102b926e3810a887be5b05da2b9ec9d223991
