### ISSUE TITLE
Cannot start this animator on a detached view!

### ISSUE THREAD

**Issue by Shohrukhbek** [faruktoptas/FancyShowCaseView#114]
Can you show me how to make CustomView work from Fragments for this method?
` view.findViewById(R.id.btn_action_1).setOnClickListener(new View.OnClickListener() {
                            @Override
                            public void onClick(View view) {
                                mQueue.getCurrent().hide();
                            }
                        });`

**Comment by faruktoptas** [comment]
You can read this wiki for custom views
https://github.com/faruktoptas/FancyShowCaseView/wiki/3.-Inflate-Custom-View

I think your problem is that you detach your fragment before FancyShowCaseView animation ends.

**Comment by Shohrukhbek** [comment]
Hey! That's right, it was detached before animation was ended because my Fragment has inner Fragments and app needs to show the Views from those inner ones. But, I found the solution:
` if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            view.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
                @TargetApi(Build.VERSION_CODES.LOLLIPOP)
                @Override
                public void onLayoutChange(View v, int left, int top, int right, int bottom,
                                           int oldLeft, int oldTop, int oldRight, int oldBottom) {
                    v.removeOnLayoutChangeListener(this);
                   **showIntro();**
                }
            });
        }`
Thanks for this nice lib 👍
