### ISSUE TITLE
Recyclerview : Onfocus to the list item BEFORE it's been pressed/click

### ISSUE THREAD

**Issue by thundenilla** [faruktoptas/FancyShowCaseView#116]
Hi. How to focus only for the single item of the list ? ie situation: 

Splash screen > dashboard (a list) > auto focus on the first item of the list with show case. ( Right before select the item ) 

Thanks mate !

@faruktoptas

**Comment by faruktoptas** [comment]
Hi @thundenilla,

Here is an example for recyclerview https://github.com/faruktoptas/FancyShowCaseView/blob/master/app/src/main/java/me/toptas/fancyshowcasesample/RecyclerViewActivity.java

You should do it in onBindViewHolder method of adapter.

**Comment by faruktoptas** [comment]
Can you share information listed in the [sample issue](https://github.com/faruktoptas/FancyShowCaseView/issues/113) please?

**Comment by faruktoptas** [comment]
Sample added to focus RecyclerView item after loading.
