### ISSUE TITLE
Ad at the top causes Focus to be Off

### ISSUE THREAD

**Issue by grndvl1** [faruktoptas/FancyShowCaseView#117]
If I place an banner ad at the top using the standard DFP library(com.google.android.gms.ads), and I have a focus on any item in the activity, the center is off.  If I remove the ad code and layout placement the centering of the Focus is spot on.

**Comment by faruktoptas** [comment]
Can you share a screen shot please?

**Comment by grndvl1** [comment]
Can't cause company I work for won't like that.  I did find a solution though, I have to use 
`.fitSystemWindows(true)`
for it to not be off by 50 pixels.
