### ISSUE TITLE
Scrolling Issue

### ISSUE THREAD

**Issue by deepakcipl** [faruktoptas/FancyShowCaseView#119]
I have a scroll view and need to focus different views among of them some views appear when user scroll the device screen. I am using queuing multiple instances. It should be auto scroll the layout and should focus on view which are visible after scrolling. Please let me know how to achieve this task.

**Comment by faruktoptas** [comment]
Queue doesn't support such a behaviour. You have to handle without a queue. You can follow the steps below:

- Listen for the scroll when view to be focused is visible show first FancyShowCase
- After first instance is closed manually scroll then show second FancyShowCase
- Repeat until the last view to be focused

**Comment by franquicidad** [comment]
hello deepakcipl where you able to solve this . If so can you please share how you did it please?
