### ISSUE TITLE
Hide on backPress

### ISSUE THREAD

**Issue by faruktoptas** [faruktoptas/FancyShowCaseView#12]

**Comment by eanurag** [comment]
There is already a `hide()` in `FancyShowCaseView`. Shouldn't the responsibility of calling `hide()` be delegated to the caller Activity's `onBackPressed()`?

**Comment by faruktoptas** [comment]
Yes it can be like that. But if an `Activity` has multiple instances of `FancyShowCaseView`. Each of them should be handled in `onBackPressed()`. Assume that a static method `FancyShowCaseView.isVisible() `can check if any instance is visible, then `FancyShowCaseView.hide() `method hides the currently visible instance. This is an approach, we can choose a better one.
