### ISSUE TITLE
Media files removed from project files

### ISSUE THREAD

**Issue by yerenutku** [faruktoptas/FancyShowCaseView#13]
Gif
![fancyshowcase](https://cloud.githubusercontent.com/assets/8283200/23941893/8fb92934-097b-11e7-9626-2c4b2d15b8ca.gif)

**Comment by faruktoptas** [comment]
![fancy_0 0 4_1](https://cloud.githubusercontent.com/assets/1595227/24331187/ad143b80-1237-11e7-919c-36111c1ce559.gif)
![fancy_0 0 4_2](https://cloud.githubusercontent.com/assets/1595227/24331189/afec8d9e-1237-11e7-986d-0ab7c44db7c7.gif)

**Comment by faruktoptas** [comment]
![screen shot 2017-04-06 at 18 03 57](https://cloud.githubusercontent.com/assets/1595227/24761139/38a1d324-1af3-11e7-8d7c-5bef3a7acc55.png)

**Comment by faruktoptas** [comment]
<img width="972" alt="screen shot 2017-04-06 at 16 23 11" src="https://user-images.githubusercontent.com/1595227/44987645-908b4d80-af90-11e8-922d-ac7426eb9eb1.png">
