### ISSUE TITLE
I have received fabric crash on multiple devices

### ISSUE THREAD

**Issue by atif-afridi** [faruktoptas/FancyShowCaseView#131]
## Fatal Exception: java.lang.IllegalStateException
Cannot start this animator on a detached view!

Android versions : 5.1,5.1.1 and 7.1.1

**Comment by atif-afridi** [comment]
Fatal Exception: java.lang.IllegalStateException: Cannot start this animator on a detached view!
       at android.view.RenderNode.addAnimator(RenderNode.java:792)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:301)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:283)
       at android.animation.RevealAnimator.(RevealAnimator.java:37)
       at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:71)
       at me.toptas.fancyshowcase.FancyShowCaseView.doCircularExitAnimation(Unknown Source)
       at me.toptas.fancyshowcase.FancyShowCaseView.hide(Unknown Source)
       at me.toptas.fancyshowcase.FancyShowCaseQueue.add(Unknown Source)
       at com.es.triv.ui.activities.ProfileActivity$27$2.onClick(Unknown Source)
       at android.view.View.performClick(View.java:6312)
       at android.widget.TextView.performClick(TextView.java:11202)
       at android.view.View$PerformClick.run(View.java:23985)



thanks for the beautiful lib ...

**Comment by faruktoptas** [comment]
Hi @atif-afridi ,
You finish the activity before exit animation ends. You should finish the activity after animation end. There is a listener for animation `builder.animationListener(listener)`

**Comment by atif-afridi** [comment]
@faruktoptas  i dont want to finisht the activity i mean may be user switch to other activity but it shouldnt not crash if user changes the screen .. how can i use builder.animationListener(listener) to handle the crash rather then closing the activity ?
thanks

**Comment by atif-afridi** [comment]
i have used this fancyview for tutorial screen which is place above my main screen of app from where your navigates to other screens. and this animation is on showed when user is registered for the first time i.e this screen is displayed only once. how can i handle this crash ? if you need more details i can provide.

**Comment by faruktoptas** [comment]
@atif-afridi I saw the problem. I must add `isAttachedToWindow` check in `doCircularExitAnimation` method. If you don't handle backPress it may cause this crash. As a workaround Can you override onBackPressed() method of your base activity like below?
```kotlin
override fun onBackPressed() {
	if (FancyShowCaseView.isVisible(this)) {
	    FancyShowCaseView.hideCurrent(this)
	} else {
	    super.onBackPressed()
	}
}
```
When user clicks back button once fancyShowCaseView will close. At the second time activity will finish.
I will fix the bug asap.

**Comment by faruktoptas** [comment]
Can you share the code that you create/show and hide the fancyShowCaseView?

**Comment by atif-afridi** [comment]
yes sure ...

private FancyShowCaseView leaderView;

 leaderView = new FancyShowCaseView.Builder(this)
                .focusOn(binding.llLeaderBoard)
                .backgroundColor(ContextCompat.getColor(this, R.color.guide_bg_light_pink))
                .customView(R.layout.layout_learderboard_view, new OnViewInflateListener() {
                    @Override
                    public void onViewInflated(@NonNull View view) {
                        setAnimatedContent(view, leaderView);
                    }
                })
                .build();

/-- some others animations are also added here --/

/-- after all view are added for animations  --/

mQueue = new FancyShowCaseQueue();
mQueue.add(leaderView);
if (!isFinishing()) {
            mQueue.show();
        }

**Comment by atif-afridi** [comment]
i have added 

if (FancyShowCaseView.isVisible(this)) {
	    FancyShowCaseView.hideCurrent(this)
	}


before opening any other activity. it looks safe to me !

**Comment by faruktoptas** [comment]
With the next release, I will add check the view is attached before the exit animation

**Comment by atif-afridi** [comment]
@faruktoptas  hey bro i just received the crash for the new changes i implemented previous kindly have a look when get time thanks


```
Fatal Exception: java.lang.IllegalStateException: Cannot start this animator on a detached view!
       at android.view.RenderNode.addAnimator(RenderNode.java:786)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:297)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:279)
       at android.animation.RevealAnimator.(RevealAnimator.java:37)
       at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:71)
       at me.toptas.fancyshowcase.FancyShowCaseView.doCircularExitAnimation(Unknown Source)
       at me.toptas.fancyshowcase.FancyShowCaseView.hideCurrent(Unknown Source)
       at me.toptas.fancyshowcase.FancyShowCaseView.hideCurrent(Unknown Source)
       at com.es.triv.ui.activities.ProfileActivity.openMainActivity(Unknown Source)
```

**Comment by faruktoptas** [comment]
Hi @atif-afridi 
It looks like the same crash. Did you use the library from the source code?

**Comment by faruktoptas** [comment]
I've just released the 1.1.2 version. It will fix your problem.

**Comment by atif-afridi** [comment]
ok thanks a lot will try it :)

**Comment by faruktoptas** [comment]
You're welcome :) 
Do you mind if I add your app to the apps using this library list in Readme?

**Comment by melamr** [comment]
hello,
i've run into the same issue while using a queue.
mFancyshowcaseView.hide() crashes, the solution for me was
mClickListener = new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //fancyShowCaseView.hide();
                queue.getCurrent().hide();
            }
        };
hope it can help others :)

**Comment by faruktoptas** [comment]
@melamr Sure. There is only one instance attached. If you try to hide an unattached instance you got this error. `queue.getCurrent()` returns the active instance.

**Comment by atif-afridi** [comment]
@faruktoptas  sure but for now we have shifted from firebase to our own server so reviews are not good now a days :p 

this is the link for the app .. its a live game show in pakistan


https://play.google.com/store/apps/details?id=com.es.triv

thanks :)
