### ISSUE TITLE
Pass inflated view in customView()

### ISSUE THREAD

**Issue by Ishwor-Shrestha** [faruktoptas/FancyShowCaseView#136]
customView() function only accepts a layout id. Would it be possible to have an option to pass an inflated view instead

**Comment by faruktoptas** [comment]
@Ishwor-Shrestha why do you need this? You can use an empty Relative/LinearLayout resource then add your inflated view with `addView()` in `onViewInflated(view:View)` method.

**Comment by Ishwor-Shrestha** [comment]
My bad. I didn't notice OnViewInflateListener returns the inflated view.
