### ISSUE TITLE
Adding a DismissListener to a FancyShowCaseQueue 

### ISSUE THREAD

**Issue by skydschmidt** [faruktoptas/FancyShowCaseView#138]
### Adding a DismissListener to a FancyShowCaseQueue 
If I use a FancyShowCaseQueue and terminate it with queue.cancel(), I have no way of knowing. Because internally in the FancyShowCaseQueue the DismissListener of the FancyShowCaseView is overwritten with the one of the queue.
But I don't have the possibility to change the behaviour of the queue in case of a dismiss. 

Is there a way I overlook? Or should the queue just get a DismissListener as attributes instead of inheriting from it? Then the behavior like the CompletedListener could be used. Alternatively the FancyShowCaseQueue would have to be marked as open, so that I can overwrite the functions in a derived class.

**Comment by faruktoptas** [comment]
@skydschmidt I couldn't understand the exact problem can you describe the issue with the steps below?
* Expected behavior
* Actual behavior:
* Steps to reproduce the problem:

**Comment by skydschmidt** [comment]
Hi @faruktoptas , Excuse my not so understandable execution.

I created a gist based on your "CustomQueueActivity" to clarify what I mean. (https://gist.github.com/skydschmidt/311e416e618e94d1bd52bfbae41c062f)

I add a DismissListener to all three FancyShowCaseView objects. 
My expectation would be that if I go through the queue, for each FancyShowCaseView object that is no longer displayed it should call the onDismiss function and I see the log output. But that's not so. I never see "onDismiss" or "onSkipped".

Also if i click the close button on fancyShowCaseView2 which aborts the queue, i would expect onDismiss to be called from the second view. but that doesn't happen either.

I hope that could explain my problem/question better.

**Comment by faruktoptas** [comment]
@skydschmidt sorry for late reply. I've seen the problem the DismissListener in the queue overrides your listener. I will fix it asap.

**Comment by skydschmidt** [comment]
Thx

**Comment by faruktoptas** [comment]
@skydschmidt I've fixed it. You can try with 1.1.5 version.

**Comment by skydschmidt** [comment]
@faruktoptas thx. works fine!
