### ISSUE TITLE
Double Touch issue

### ISSUE THREAD

**Issue by udongeex** [faruktoptas/FancyShowCaseView#139]
When I double touch the view (very fast, within 1 second), the animation did flash two times before closed.
Is there a way to stop it ? Thanks a lot

**Comment by faruktoptas** [comment]
@udongeex Use `animationListener` to find out if the view is still animating. Don't do anything if there is an ongoing animation. Also you can set `closeOnTouch(false)` to prevent double touch to close the view.
Here is a sample usage for animation listener:

```kotlin
FancyShowCaseView.Builder(this)
    .focusOn(it)
    .title("Focus on View only once")
    .animationListener(object: AnimationListener {
        override fun onEnterAnimationEnd() {

        }

        override fun onExitAnimationEnd() {
            
        }
    })
    .build()
    .show()
```

**Comment by udongeex** [comment]
Thanks you @faruktoptas ,just what I need 👍
