### ISSUE TITLE
Going one step back in FancyShowCaseQueue

### ISSUE THREAD

**Issue by andzejsw** [faruktoptas/FancyShowCaseView#140]
No method to go back to previous queue step. Only way so far i discovered is to manually add the one step, who was before and all steps who will follow it. And then just call: 
`queue.getCurrent().hide();`
wich one closes current step and opens back step, cause it is next in queue.

**Comment by faruktoptas** [comment]
@andzejsw queue mechanism doesn't support going back now. You should create your own queue. Set an `animationListener` in builder then show the next/previous instance in `onExitAnimationEnd` method.

**Comment by andzejsw** [comment]
> @andzejsw queue mechanism doesn't support going back now. You should create your own queue. Set an `animationListener` in builder then show the next/previous instance in `onExitAnimationEnd` method.

Ok. Tnx for answer.

**Comment by andzejsw** [comment]
> @andzejsw queue mechanism doesn't support going back now. You should create your own queue. Set an `animationListener` in builder then show the next/previous instance in `onExitAnimationEnd` method.

Tnx again. I made it working!

**Comment by rodrigo364** [comment]
Hello, I would like a tip on how you managed to implement the backward option in lib

**Comment by faruktoptas** [comment]
@rodrigo364 You shouldn't use a queue. Create all instances and set order as you want. Set an `animationListener` in builder then show the next/previous instance in `onExitAnimationEnd` method

**Comment by gabrielbrandaodelima** [comment]
> > @andzejsw queue mechanism doesn't support going back now. You should create your own queue. Set an `animationListener` in builder then show the next/previous instance in `onExitAnimationEnd` method.
> 
> Tnx again. I made it working!

Can you post an example? I'm not sure if I understood how to do it.

**Comment by andzejsw** [comment]
> > > @andzejsw queue mechanism doesn't support going back now. You should create your own queue. Set an `animationListener` in builder then show the next/previous instance in `onExitAnimationEnd` method.
> > 
> > 
> > Tnx again. I made it working!
> 
> Can you post an example? I'm not sure if I understood how to do it.

My Tutorial.java file:

```
public class Tutorial {
    private String TAG = Tutorial.class.getSimpleName();
    private FancyShowCaseView startStep, switchStep, numberSelectStep, menuStep, contactsStep, callHistorysStep, liveCallsMenuStep, liveCallsStep, endStep, bubblesStep;
    private Activity mActivity;
    private ArrayList<FancyShowCaseView> queue = new ArrayList<>();
    private ArrayList<TutorialStep> stepList = new ArrayList<>();
    private OfflineDataRepository mData = new OfflineDataRepository();

    private int stepActive = 0;
    private String endContext = "";

    public Tutorial(Context context) {
        this.mActivity = (Activity) context;
        init();
    }

    public Tutorial(Context context, int stepActive) {
        this.mActivity = (Activity) context;
        this.stepActive = stepActive;
        init();
    }

    private void init() {
        Intent mainIntent = new Intent(mActivity, MainActivity.class);
        Intent liveCallsIntent = new Intent(mActivity, LiveCallsActivity.class);

        liveCallsIntent.addFlags(Intent.FLAG_ACTIVITY_NO_ANIMATION | Intent.FLAG_ACTIVITY_SINGLE_TOP);
        mainIntent.addFlags(Intent.FLAG_ACTIVITY_NO_ANIMATION | Intent.FLAG_ACTIVITY_CLEAR_TOP);

        Options commonOptions = new Options(true, true, mainIntent);
        Options liveCallsMenuOptions = new Options(true, false, null);
        Options liveCallsOptions = new Options(false, true, liveCallsIntent);

        startStep = buildStep(0, R.string.tutorial_main_title, "START", null);
        switchStep = buildStep(R.id.switchState, R.string.tutorial_switch_title, "SWITCH", null);
        numberSelectStep = buildStep(R.id.textViewNumber, R.string.tutorial_number_select_title, "NUMBER_SELECT", commonOptions);
        menuStep = buildStep(0, R.string.tutorial_menu_title, "SHOW_MENU", null);
        contactsStep = buildStep(R.id.KEY_CONTACTS, R.string.tutorial_menu_contacts_title, "SHOW_MENU", null);
        callHistorysStep = buildStep(R.id.KEY_CALL_HISTORY, R.string.tutorial_menu_call_history_title, "SHOW_MENU", null);
        liveCallsMenuStep = buildStep(R.id.KEY_LIVE_CALLS, R.string.tutorial_menu_live_calls_title, "SHOW_MENU", liveCallsMenuOptions);
        liveCallsStep = buildStep(R.id.live_call_container, R.string.tutorial_live_calls_title, "LIVE_CALLS", liveCallsOptions);
        bubblesStep = buildStep(0, R.string.tutorial_bubbles_title, "BUBBLES", null);
        endStep = buildStep(0, R.string.tutorial_end_title, "END", null);

        queue.add(startStep);
        queue.add(switchStep);
        queue.add(numberSelectStep);
        queue.add(menuStep);
        queue.add(contactsStep);
        queue.add(callHistorysStep);
        queue.add(liveCallsMenuStep);
        queue.add(liveCallsStep);
        queue.add(bubblesStep);
        queue.add(endStep);

        queue.get(stepActive).show();
    }

    private FancyShowCaseView buildStep(int v, int title, String tag, Options options) {
        String t = mActivity.getString(title);
        TutorialStep step = new TutorialStep(v, t, tag, options);
        stepList.add(step);
        return buildFancyShowCaseView(v, t, tag, options);
    }

    private FancyShowCaseView buildFancyShowCaseView(int v, final String title, String tag, Options options) {
        LastShownStep lStep = new LastShownStep(stepActive, false);
        if(options != null) {
            if(options.openOnRedirect()) {
                lStep = new LastShownStep(stepActive, true);
            }
        }

        if(tag != null && tag.equals("BUBBLES")) {
            if(stepList.get(stepActive).getTag().equals(tag)) {
                ServicesActions.startBubbleService(1546, mActivity); //Bubble service test start
            }
        } else {
            if (TransferBubblesService.isRunning()) {
                ServicesActions.stopBubbleService(mActivity);
            }
        }

        mData.saveObject("TUTORIAL_SEEN", lStep);
        FancyShowCaseView.Builder vBuilder = new FancyShowCaseView.Builder(mActivity);
        if (v != 0) {
            View focusView = mActivity.findViewById(v);
            if (focusView != null) {
                vBuilder = vBuilder.focusOn(focusView).focusShape(FocusShape.ROUNDED_RECTANGLE);

                if(options != null) {
                    if(options.isTouchEnabled()) {
                        vBuilder = vBuilder.enableTouchOnFocusedView(true);
                    }
                } else if(tag != null && !tag.equals("SHOW_MENU")) {
                    vBuilder = vBuilder.enableTouchOnFocusedView(true);
                }
            }
        }
        return vBuilder.animationListener(new AnimationListener() {
            @Override
            public void onEnterAnimationEnd() {

            }

            @Override
            public void onExitAnimationEnd() {
                if (!endContext.equals("CLOSE")) {
                    TutorialStep step = stepList.get(stepActive);
                    String tag = step.getTag();
                    Options o = step.getOptions();
                    FancyShowCaseView fvi = buildFancyShowCaseView(step.getView(), step.getTitle(), tag, o);
                    final DrawerLayout navDrawer = mActivity.findViewById(R.id.drawer_layout);
                    queue.set(stepActive, fvi);
                    if (tag != null && tag.equals("SHOW_MENU")) {
                        if(endContext.equals("NEXT")) {
                            if (!navDrawer.isDrawerOpen(GravityCompat.START)) {
                                new android.os.Handler().postDelayed(
                                    new Runnable() {
                                        public void run() {
                                            navDrawer.openDrawer(Gravity.START);
                                        }
                                    },
                                    1000);
                            }
                            queue.get(stepActive).show();
                        } else {
                            if (navDrawer != null && !navDrawer.isDrawerOpen(GravityCompat.START)) {
                                navDrawer.openDrawer(Gravity.START);
                                new android.os.Handler().postDelayed(
                                    new Runnable() {
                                        public void run() {
                                            queue.get(stepActive).show();
                                        }
                                    },
                                    300);
                            } else {
                                queue.get(stepActive).show();
                            }
                        }
                    } else {
                        if (navDrawer.isDrawerOpen(GravityCompat.START))
                            navDrawer.closeDrawer(Gravity.START);
                        if(o != null && o.getIntent() != null && tag != null) {
                            if (mActivity instanceof MainActivity && !tag.equals("NUMBER_SELECT")) {
                                mActivity.startActivity(o.getIntent());
                            } else if(mActivity instanceof LiveCallsActivity && !tag.equals("LIVE_CALLS")) {
                                mActivity.startActivity(o.getIntent());
                            }
                        }
                        queue.get(stepActive).show();
                    }
                } else {
                    if (TransferBubblesService.isRunning()) {
                        ServicesActions.stopBubbleService(mActivity);
                    }
                    mData.saveObject("TUTORIAL_CLOSED", true);
                }
            }
        })
                .backgroundColor(Color.parseColor("#60000000"))
                .customView(R.layout.tutorial, new OnViewInflateListener() {
                    @Override
                    public void onViewInflated(@NotNull View view) {
                        // Prepare font
                        Typeface iconFont = FontManager.getTypeface(mActivity, FontManager.ICOMOON);
                        FontManager.markAsIconContainer(view.findViewById(R.id.tutorialActions), iconFont);

                        // Prepare view
                        ImageView btnClose = view.findViewById(R.id.close);
                        final RelativeLayout btnBack = view.findViewById(R.id.back_btn_layout);
                        final RelativeLayout btnNext = view.findViewById(R.id.next_btn_layout);
                        TextView t = view.findViewById(R.id.title);

                        t.setText(title);

                        if (stepActive == 0) {
                            view.findViewById(R.id.back_btn).setVisibility(View.GONE);
                        } else if (stepActive == queue.size() - 1) {
                            view.findViewById(R.id.next_btn).setVisibility(View.GONE);
                        }

                        btnClose.setOnClickListener(new View.OnClickListener() {
                            @Override
                            public void onClick(View view) {
                                endContext = "CLOSE";
                                queue.get(stepActive).hide();
                            }
                        });
                        if (stepActive != 0) {
                            btnBack.setOnClickListener(new View.OnClickListener() {
                                @Override
                                public void onClick(View view) {
                                    endContext = "BACK";
                                    queue.get(stepActive).hide();
                                    stepActive = stepActive - 1;
                                    btnBack.setOnClickListener(null);
                                }
                            });
                        }
                        if (stepActive != queue.size() - 1) {
                            btnNext.setOnClickListener(new View.OnClickListener() {
                                @Override
                                public void onClick(View view) {
                                    endContext = "NEXT";
                                    queue.get(stepActive).hide();
                                    stepActive = stepActive + 1;
                                    btnNext.setOnClickListener(null);
                                }
                            });
                        }
                    }
                }).closeOnTouch(false)
                .build();
    }

    private class TutorialStep {
        private int view;
        private String title;
        private String tag;
        private Options options;

        private TutorialStep(int v, String title, String tag, Options options) {
            this.view = v;
            this.title = title;
            this.tag = tag;
            this.options = options;
        }

        public int getView() {
            return this.view;
        }

        public String getTitle() {
            return this.title;
        }

        public String getTag() {
            return this.tag;
        }

        public Options getOptions() {
            return this.options;
        }
    }

    private class Options {
        private boolean touchEnabled;
        private boolean openOnRedirect;
        private Intent intent;

        private Options(boolean touchEnabled, boolean openOnRedirect, Intent intent) {
            this.touchEnabled = touchEnabled;
            this.openOnRedirect = openOnRedirect;
            this.intent = intent;
        }

        private boolean isTouchEnabled() {
            return this.touchEnabled;
        }

        private boolean openOnRedirect() {
            return this.openOnRedirect;
        }

        private Intent getIntent() {
            return this.intent;
        }
    }
}
```

**Comment by gabrielbrandaodelima** [comment]
> > > > @andzejsw queue mechanism doesn't support going back now. You should create your own queue. Set an `animationListener` in builder then show the next/previous instance in `onExitAnimationEnd` method.
> > > 
> > > 
> > > Tnx again. I made it working!
> > 
> > 
> > Can you post an example? I'm not sure if I understood how to do it.
> 
> My Tutorial.java file:
> 
> ```
> public class Tutorial {
>     private String TAG = Tutorial.class.getSimpleName();
>     private FancyShowCaseView startStep, switchStep, numberSelectStep, menuStep, contactsStep, callHistorysStep, liveCallsMenuStep, liveCallsStep, endStep, bubblesStep;
>     private Activity mActivity;
>     private ArrayList<FancyShowCaseView> queue = new ArrayList<>();
>     private ArrayList<TutorialStep> stepList = new ArrayList<>();
>     private OfflineDataRepository mData = new OfflineDataRepository();
> 
>     private int stepActive = 0;
>     private String endContext = "";
> 
>     public Tutorial(Context context) {
>         this.mActivity = (Activity) context;
>         init();
>     }
> 
>     public Tutorial(Context context, int stepActive) {
>         this.mActivity = (Activity) context;
>         this.stepActive = stepActive;
>         init();
>     }
> 
>     private void init() {
>         Intent mainIntent = new Intent(mActivity, MainActivity.class);
>         Intent liveCallsIntent = new Intent(mActivity, LiveCallsActivity.class);
> 
>         liveCallsIntent.addFlags(Intent.FLAG_ACTIVITY_NO_ANIMATION | Intent.FLAG_ACTIVITY_SINGLE_TOP);
>         mainIntent.addFlags(Intent.FLAG_ACTIVITY_NO_ANIMATION | Intent.FLAG_ACTIVITY_CLEAR_TOP);
> 
>         Options commonOptions = new Options(true, true, mainIntent);
>         Options liveCallsMenuOptions = new Options(true, false, null);
>         Options liveCallsOptions = new Options(false, true, liveCallsIntent);
> 
>         startStep = buildStep(0, R.string.tutorial_main_title, "START", null);
>         switchStep = buildStep(R.id.switchState, R.string.tutorial_switch_title, "SWITCH", null);
>         numberSelectStep = buildStep(R.id.textViewNumber, R.string.tutorial_number_select_title, "NUMBER_SELECT", commonOptions);
>         menuStep = buildStep(0, R.string.tutorial_menu_title, "SHOW_MENU", null);
>         contactsStep = buildStep(R.id.KEY_CONTACTS, R.string.tutorial_menu_contacts_title, "SHOW_MENU", null);
>         callHistorysStep = buildStep(R.id.KEY_CALL_HISTORY, R.string.tutorial_menu_call_history_title, "SHOW_MENU", null);
>         liveCallsMenuStep = buildStep(R.id.KEY_LIVE_CALLS, R.string.tutorial_menu_live_calls_title, "SHOW_MENU", liveCallsMenuOptions);
>         liveCallsStep = buildStep(R.id.live_call_container, R.string.tutorial_live_calls_title, "LIVE_CALLS", liveCallsOptions);
>         bubblesStep = buildStep(0, R.string.tutorial_bubbles_title, "BUBBLES", null);
>         endStep = buildStep(0, R.string.tutorial_end_title, "END", null);
> 
>         queue.add(startStep);
>         queue.add(switchStep);
>         queue.add(numberSelectStep);
>         queue.add(menuStep);
>         queue.add(contactsStep);
>         queue.add(callHistorysStep);
>         queue.add(liveCallsMenuStep);
>         queue.add(liveCallsStep);
>         queue.add(bubblesStep);
>         queue.add(endStep);
> 
>         queue.get(stepActive).show();
>     }
> 
>     private FancyShowCaseView buildStep(int v, int title, String tag, Options options) {
>         String t = mActivity.getString(title);
>         TutorialStep step = new TutorialStep(v, t, tag, options);
>         stepList.add(step);
>         return buildFancyShowCaseView(v, t, tag, options);
>     }
> 
>     private FancyShowCaseView buildFancyShowCaseView(int v, final String title, String tag, Options options) {
>         LastShownStep lStep = new LastShownStep(stepActive, false);
>         if(options != null) {
>             if(options.openOnRedirect()) {
>                 lStep = new LastShownStep(stepActive, true);
>             }
>         }
> 
>         if(tag != null && tag.equals("BUBBLES")) {
>             if(stepList.get(stepActive).getTag().equals(tag)) {
>                 ServicesActions.startBubbleService(1546, mActivity); //Bubble service test start
>             }
>         } else {
>             if (TransferBubblesService.isRunning()) {
>                 ServicesActions.stopBubbleService(mActivity);
>             }
>         }
> 
>         mData.saveObject("TUTORIAL_SEEN", lStep);
>         FancyShowCaseView.Builder vBuilder = new FancyShowCaseView.Builder(mActivity);
>         if (v != 0) {
>             View focusView = mActivity.findViewById(v);
>             if (focusView != null) {
>                 vBuilder = vBuilder.focusOn(focusView).focusShape(FocusShape.ROUNDED_RECTANGLE);
> 
>                 if(options != null) {
>                     if(options.isTouchEnabled()) {
>                         vBuilder = vBuilder.enableTouchOnFocusedView(true);
>                     }
>                 } else if(tag != null && !tag.equals("SHOW_MENU")) {
>                     vBuilder = vBuilder.enableTouchOnFocusedView(true);
>                 }
>             }
>         }
>         return vBuilder.animationListener(new AnimationListener() {
>             @Override
>             public void onEnterAnimationEnd() {
> 
>             }
> 
>             @Override
>             public void onExitAnimationEnd() {
>                 if (!endContext.equals("CLOSE")) {
>                     TutorialStep step = stepList.get(stepActive);
>                     String tag = step.getTag();
>                     Options o = step.getOptions();
>                     FancyShowCaseView fvi = buildFancyShowCaseView(step.getView(), step.getTitle(), tag, o);
>                     final DrawerLayout navDrawer = mActivity.findViewById(R.id.drawer_layout);
>                     queue.set(stepActive, fvi);
>                     if (tag != null && tag.equals("SHOW_MENU")) {
>                         if(endContext.equals("NEXT")) {
>                             if (!navDrawer.isDrawerOpen(GravityCompat.START)) {
>                                 new android.os.Handler().postDelayed(
>                                     new Runnable() {
>                                         public void run() {
>                                             navDrawer.openDrawer(Gravity.START);
>                                         }
>                                     },
>                                     1000);
>                             }
>                             queue.get(stepActive).show();
>                         } else {
>                             if (navDrawer != null && !navDrawer.isDrawerOpen(GravityCompat.START)) {
>                                 navDrawer.openDrawer(Gravity.START);
>                                 new android.os.Handler().postDelayed(
>                                     new Runnable() {
>                                         public void run() {
>                                             queue.get(stepActive).show();
>                                         }
>                                     },
>                                     300);
>                             } else {
>                                 queue.get(stepActive).show();
>                             }
>                         }
>                     } else {
>                         if (navDrawer.isDrawerOpen(GravityCompat.START))
>                             navDrawer.closeDrawer(Gravity.START);
>                         if(o != null && o.getIntent() != null && tag != null) {
>                             if (mActivity instanceof MainActivity && !tag.equals("NUMBER_SELECT")) {
>                                 mActivity.startActivity(o.getIntent());
>                             } else if(mActivity instanceof LiveCallsActivity && !tag.equals("LIVE_CALLS")) {
>                                 mActivity.startActivity(o.getIntent());
>                             }
>                         }
>                         queue.get(stepActive).show();
>                     }
>                 } else {
>                     if (TransferBubblesService.isRunning()) {
>                         ServicesActions.stopBubbleService(mActivity);
>                     }
>                     mData.saveObject("TUTORIAL_CLOSED", true);
>                 }
>             }
>         })
>                 .backgroundColor(Color.parseColor("#60000000"))
>                 .customView(R.layout.tutorial, new OnViewInflateListener() {
>                     @Override
>                     public void onViewInflated(@NotNull View view) {
>                         // Prepare font
>                         Typeface iconFont = FontManager.getTypeface(mActivity, FontManager.ICOMOON);
>                         FontManager.markAsIconContainer(view.findViewById(R.id.tutorialActions), iconFont);
> 
>                         // Prepare view
>                         ImageView btnClose = view.findViewById(R.id.close);
>                         final RelativeLayout btnBack = view.findViewById(R.id.back_btn_layout);
>                         final RelativeLayout btnNext = view.findViewById(R.id.next_btn_layout);
>                         TextView t = view.findViewById(R.id.title);
> 
>                         t.setText(title);
> 
>                         if (stepActive == 0) {
>                             view.findViewById(R.id.back_btn).setVisibility(View.GONE);
>                         } else if (stepActive == queue.size() - 1) {
>                             view.findViewById(R.id.next_btn).setVisibility(View.GONE);
>                         }
> 
>                         btnClose.setOnClickListener(new View.OnClickListener() {
>                             @Override
>                             public void onClick(View view) {
>                                 endContext = "CLOSE";
>                                 queue.get(stepActive).hide();
>                             }
>                         });
>                         if (stepActive != 0) {
>                             btnBack.setOnClickListener(new View.OnClickListener() {
>                                 @Override
>                                 public void onClick(View view) {
>                                     endContext = "BACK";
>                                     queue.get(stepActive).hide();
>                                     stepActive = stepActive - 1;
>                                     btnBack.setOnClickListener(null);
>                                 }
>                             });
>                         }
>                         if (stepActive != queue.size() - 1) {
>                             btnNext.setOnClickListener(new View.OnClickListener() {
>                                 @Override
>                                 public void onClick(View view) {
>                                     endContext = "NEXT";
>                                     queue.get(stepActive).hide();
>                                     stepActive = stepActive + 1;
>                                     btnNext.setOnClickListener(null);
>                                 }
>                             });
>                         }
>                     }
>                 }).closeOnTouch(false)
>                 .build();
>     }
> 
>     private class TutorialStep {
>         private int view;
>         private String title;
>         private String tag;
>         private Options options;
> 
>         private TutorialStep(int v, String title, String tag, Options options) {
>             this.view = v;
>             this.title = title;
>             this.tag = tag;
>             this.options = options;
>         }
> 
>         public int getView() {
>             return this.view;
>         }
> 
>         public String getTitle() {
>             return this.title;
>         }
> 
>         public String getTag() {
>             return this.tag;
>         }
> 
>         public Options getOptions() {
>             return this.options;
>         }
>     }
> 
>     private class Options {
>         private boolean touchEnabled;
>         private boolean openOnRedirect;
>         private Intent intent;
> 
>         private Options(boolean touchEnabled, boolean openOnRedirect, Intent intent) {
>             this.touchEnabled = touchEnabled;
>             this.openOnRedirect = openOnRedirect;
>             this.intent = intent;
>         }
> 
>         private boolean isTouchEnabled() {
>             return this.touchEnabled;
>         }
> 
>         private boolean openOnRedirect() {
>             return this.openOnRedirect;
>         }
> 
>         private Intent getIntent() {
>             return this.intent;
>         }
>     }
> }
> ```

Thx for the code. 

I was trying to do as you did. 

Created an Array of FancyShowCaseView, but when I call queue.get(0).show(); 

It is not working... 

Do you know why?

`
        mFancyShowCaseView = FancyShowCaseView.Builder(this)
                .showOnce("init")
                .customView(R.layout.layout_tutorial_dynamic, object : OnViewInflateListener {
                    override fun onViewInflated(view: View) {
                        oneStep(view)
                    }
                })
                .closeOnTouch(false)
                .build()

        val mFancyShowCaseView2 = FancyShowCaseView.Builder(this)
                .focusOn(content_name)
                .focusShape(FocusShape.ROUNDED_RECTANGLE)
                .roundRectRadius(35)
                .enableTouchOnFocusedView(true)
                .customView(R.layout.layout_tutorial_dynamic, object : OnViewInflateListener {
                    override fun onViewInflated(view: View) {

                        val lnlJump = (view as RelativeLayout).findViewById<LinearLayout>(R.id.content_option_tutorial)
                        val lnlTutorialOne = (view).findViewById<LinearLayout>(R.id.content_tutorial)

                        val txtTitle = (view).findViewById<TextView>(R.id.custom_view_tutorial)
                        txtTitle.text = getString(R.string.title_tutorial_sub)

                        val txtMsg = (view).findViewById<TextView>(R.id.txt_info_tutorial_parts)
                        txtMsg.text = getString(R.string.title_tutorial_msg)


                        val imgNext = (view).findViewById<ImageView>(R.id.btn_icon_next)
                        val imgBack = (view).findViewById<ImageView>(R.id.btn_icon_back)
                        val viewColorSelected = (view).findViewById<View>(R.id.view_two)

                        imgBack?.setOnClickListener {
//                            resetFirstQueue()/
                        }

                        lnlJump.gone()
                        lnlTutorialOne.visible()

                        imgNext?.setOnClickListener {
                            viewColorSelected.backgroundTintList = resources?.getColorStateList(R.color.colorOrange)
                            navController?.navigate(R.id.cadUpdatePersonalDataEditFragment)
//                            queue.current?.hide()
                        }

                    }
                })
                .closeOnTouch(false)

                .build()



        mFancyShowCaseView?.let { one ->

            mFancyShowCaseView2?.let {
                queue.add(one)
                queue.add(it)
            }
        }

        if (queue.isNotEmpty())
            queue[0]!!.show()
`

**Comment by gabrielbrandaodelima** [comment]
@andzejsw When you show a previous step, does your background also gets black, and not transparent?

**Comment by andzejsw** [comment]
> @andzejsw When you show a previous step, does your background also gets black, and not transparent?

If I remember correctly, background was transparent. But I haven't worked long time with this project. It have been more than a year.

**Comment by gabrielbrandaodelima** [comment]
> > @andzejsw When you show a previous step, does your background also gets black, and not transparent?
> 
> If I remember correctly, background was transparent. But I haven't worked long time with this project. It have been more than a year.

I see ok thanks anyway. 

Just last question. In your app, when you go one step back, does your FancyShowView also duplicate the focus view? 
When I'm going one step back, and then forward, and then back again, each time I go back once, it replicates the focus view, like it's creating a stack of focusing views.
