### ISSUE TITLE
View reinits multiple times

### ISSUE THREAD

**Issue by andzejsw** [faruktoptas/FancyShowCaseView#141]
I have FancyShowCaseView with animationListener. In onExitAnimationEnd i have this code: 
`queue.get(stepActive).show();`
I have A custom view . In it i have some click listeners. If i click back one, which one has this code: 
`btnBack.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View view) {
        queue.get(stepActive).hide();
        stepActive = stepActive - 1;
    }
});`, it opens view, but multiple times. As far as i understand as many times, as many i have seen that view.
Does anyone know fix?

**Comment by andzejsw** [comment]
`queue.get(stepActive).hide();`
I am not closing view correctly or what?

**Comment by andzejsw** [comment]
or listener is responsible for this issue,

**Comment by faruktoptas** [comment]
Hi @andzejsw 
Which method is triggering multiple times?

**Comment by andzejsw** [comment]
> Hi @andzejsw
> Which method is triggering multiple times?

As far as i see logs in my code, none of mine: 
'
buildStep next: 1
buildStep onExitAnimationEnd: 1
buildStep next: 2
buildStep onExitAnimationEnd: 2
buildStep back: 1
buildStep onExitAnimationEnd: 1
buildStep back: 0
buildStep onExitAnimationEnd: 0
'
Here is log from first next button click till i reach third view. and then i go from 3rd to first again.

**Comment by andzejsw** [comment]
btnNest code: 
`queue.get(stepActive).hide(); stepActive = stepActive + 1;`
btnBack code: 
`queue.get(stepActive).hide(); stepActive = stepActive - 1;`

**Comment by andzejsw** [comment]
I think i got something. Same happend if i add same view multiple times: 

queue.add(switchStep);
queue.add(switchStep);
queue.add(switchStep);

**Comment by andzejsw** [comment]
> I think i got something. Same happend if i add same view multiple times:
> 
> queue.add(switchStep);
> queue.add(switchStep);
> queue.add(switchStep);

For all cases there is same view id. But isShownBefore == false;

**Comment by andzejsw** [comment]
Only way so far to get over this issue so far which one i found is to create create new view again in onExitAnimationEnd like this: 
`
public void onExitAnimationEnd() {
    if(!tutorialClosed) {
        View vi = stepList.get(stepActive).getView();
        String ti = stepList.get(stepActive).getTitle();
        FancyShowCaseView fvi = buildStep(vi, ti);
        queue.set(stepActive, fvi);
        queue.get(stepActive).show();
    }
}
`

**Comment by faruktoptas** [comment]
Using the same instance multiple times may cause this problem. You should create new instances.

**Comment by andzejsw** [comment]
> Using the same instance multiple times may cause this problem. You should create new instances.

Ok i will do that. But still i think this should be fixed in this lib.
