### ISSUE TITLE
How to focus multiple views at same screen at a time

### ISSUE THREAD

**Issue by bhoomishah20** [faruktoptas/FancyShowCaseView#145]
Library works perfect but got stuck in below issue:
## How to focus multiple views at same screen at a time
Can we be able to focus multiple views, like add views in array? or maybe call focusOn multiple times? using this library?

Please let us know,
Thanks in Advance!

**Comment by faruktoptas** [comment]
Hi, @bhoomishah20 you can use FancyShowCaseQueue to show multiple instances as a chain. But there is no support to focus on multiple views in one instance.

**Comment by zihadrizkyef** [comment]
I think it will be great if you make the feature. So you make something like this

![image](https://user-images.githubusercontent.com/22538348/100313573-84fc2500-2fe7-11eb-83d2-b6035a03e87f.png)
