### ISSUE TITLE
Cannot start this animator on a detached view!

### ISSUE THREAD

**Issue by fajaranugrah** [faruktoptas/FancyShowCaseView#147]
Fatal Exception: java.lang.IllegalStateException
Cannot start this animator on a detached view!
me.toptas.fancyshowcase.FancyShowCaseView$7.onGlobalLayout

i show on activity and then fragment

android.view.RenderNode.addAnimator (RenderNode.java:799)
android.view.RenderNodeAnimator.setTarget (RenderNodeAnimator.java:299)
android.view.RenderNodeAnimator.setTarget (RenderNodeAnimator.java:281)
android.animation.RevealAnimator.<init> (RevealAnimator.java:37)
android.view.ViewAnimationUtils.createCircularReveal (ViewAnimationUtils.java:71)
me.toptas.fancyshowcase.FancyShowCaseView$7.onGlobalLayout (FancyShowCaseView.java:524)
android.view.ViewTreeObserver.dispatchOnGlobalLayout (ViewTreeObserver.java:945)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2295)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1437)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6886)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1029)
android.view.Choreographer.doCallbacks (Choreographer.java:841)
android.view.Choreographer.doFrame (Choreographer.java:772)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1015)
android.os.Handler.handleCallback (Handler.java:794)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:176)
android.app.ActivityThread.main (ActivityThread.java:6651)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:824)

how to fixed this problem thanks
i use this one
com.github.faruktoptas:FancyShowCaseView:1.0.0
because i use code java
and then problem on OS 8.1.0 phone Redmi 5 Plus

**Comment by faruktoptas** [comment]
Hi @fajaranugrah You are trying to close the instance after detaching the fragment from activity. Does it happen when you backPress?

**Comment by fajaranugrah** [comment]
@faruktoptas not sure, because i get this error from firebase crash

**Comment by faruktoptas** [comment]
Can you use the latest version? 1.0.0 is a buggy version for Issue #131

**Comment by fajaranugrah** [comment]
@faruktoptas after i update to 
implementation 'com.github.faruktoptas:FancyShowCaseView:1.1.5'
i got problem like this #143 but i don't know how to fixed it because i use java not kotlin
can you help me?
thanks
