### ISSUE TITLE
Focusing wrong position on Android 4.x devices

### ISSUE THREAD

**Issue by faruktoptas** [faruktoptas/FancyShowCaseView#15]

**Comment by Spettacolo83** [comment]
I still have this problem with new version 1.0.0:

![screenshot_1508117065](https://user-images.githubusercontent.com/5663188/31591613-426f26aa-b219-11e7-9559-7ee46692e53a.png)

I'm using .fitSystemWindows(true)

**Comment by faruktoptas** [comment]
@Spettacolo83 can you share your layout xml file?

**Comment by Spettacolo83** [comment]
Yes @faruktoptas this is my layout xml:

[](https://gist.github.com/Spettacolo83/203b017c1429dafce0e0900952d4902b)

**Comment by faruktoptas** [comment]
Removing `windowTranslucentStatus:true` and `windowContentOverlay:@null` from your theme will fix the problem.

**Comment by Spettacolo83** [comment]
Thank you very much @faruktoptas I solve in that way.
I removed them only for KitKat and it works!
Thank you once again!
