### ISSUE TITLE
i get this error when include library 

### ISSUE THREAD

**Issue by tarek13** [faruktoptas/FancyShowCaseView#151]
this is error
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/ContextCompat;

**Comment by faruktoptas** [comment]
Can you add the line below to app/gradle dependencies?

`implementation "androidx.appcompat:appcompat:1.0.2"`

**Comment by tarek13** [comment]
can i include library without convert my project to androidx

**Comment by sundeepkmallick** [comment]
Hi @tarek13 , Did you manage to include the library without converting the whole project to AndroidX?

**Comment by tarek13** [comment]
yes

**Comment by sundeepkmallick** [comment]
Please suggest how?

**Comment by tarek13** [comment]
i tried put it doesn't work so i need help from @faruktoptas  to solve this issue

**Comment by sundeepkmallick** [comment]
I assume, only solution is to migrate the app to AndroidX. Notify if anyone succeeded. I concluded from this discussion: https://stackoverflow.com/questions/53268865/android-x-toolsreplace-specified-at-line-for-attribute-but-no-new-value-spec

**Comment by tarek13** [comment]
thanks , but it is better to include library without androidx

**Comment by faruktoptas** [comment]
Hi @tarek13 sorry for late reply. It should work without converting to androidx. Can you share the error you see when you implement. Also your gradle file please(to see other dependencies etc.)?

**Comment by faruktoptas** [comment]
@tarek13 you can use 1.1.5 version.

**Comment by tarek13** [comment]
Great!
Thanks a lot

**Comment by karthikbala83** [comment]
@faruktoptas 

We have migrated to androidX and facing the same issue for the version 1.2.1
Any idea how to fix it?

**Comment by faruktoptas** [comment]
ContextCompat is under androidx.core:core:1.xx can you check that you have this package. If not try to add the dependencies below:
```
implementation 'androidx.core:core-ktx:1.1.0'
implementation 'androidx.appcompat:appcompat:1.1.0'
```

**Comment by karthikbala83** [comment]
@faruktoptas 

Thanks for the updated.
I've added but i'm getting below error

Duplicate class org.intellij.lang.annotations.Flow found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)

If i remove 
implementation 'androidx.core:core-ktx:1.1.0'

Then there is no error.
