### ISSUE TITLE
How to stop the view from persisting when fragment is destroyed

### ISSUE THREAD

**Issue by nofurylion** [faruktoptas/FancyShowCaseView#156]
### Steps to reproduce the problem:
1. Use navigation component
2. Call  FancyShowCaseView on fragment A
3. Press hardware back button
4. FancyShowCaseView still visible 

### How you show/hide FancyShowCaseView (in Activity or Fragment, in which method)
In Fragment onViewCreated() method I set OnClickListener to a button that execute below code:
```
FancyShowCaseView.Builder(requireActivity())
                .focusOn(transparentMain_BTN_selectRectangle)
                .title("Draw rectangle in the desired area ")
                .fitSystemWindows(true)
                .disableFocusAnimation()
                .focusShape(FocusShape.ROUNDED_RECTANGLE)
                .roundRectRadius(10)
                .build()
                .show()
```
### Specifications (Android version, Device etc.):
sdk 23

I suspect this behaviour was caused by passing activity as context `Builder(requireActivity())`.

**Comment by faruktoptas** [comment]
Hi @nofurylion,
The view is above the fragment so you should manually handle it by overriding backPress behavior.

```
override fun onBackPressed() {
    if (FancyShowCaseView.isVisible(this)) {
        FancyShowCaseView.hideCurrent(this)
    } else {
        super.onBackPressed()
    }
}
```
