### ISSUE TITLE
Text not center

### ISSUE THREAD

**Issue by Ramkumar810** [faruktoptas/FancyShowCaseView#158]
### How you show/hide FancyShowCaseView (in Activity or Fragment, in which method)

Example:
In Activity onCreate() method I use the code below to show:
```kotlin
btn_simple.setOnClickListener {
    FancyShowCaseView.Builder(this)
            .title("No Focus")
            .build()
            .show()
}
```
### Specifications (Android version, Device etc.):

**Comment by faruktoptas** [comment]
@Ramkumar810 can you share a screenshot please?

**Comment by MrSagarShah** [comment]
I am facing the same issue but only in the devices which has a notch screen.

**Comment by Ramkumar810** [comment]
sorry,  I am using custom  FancyShowCaseView.

*Regards,*
*Ramkumar* |  Principal Software Engineer
+91 9597282954 |  ramkumar.perumal@adyog.com

  <https://www.facebook.com/adyog.software.solutions>
<https://www.linkedin.com/company/adyog>  <https://twitter.com/Adyog>

**Comment by faruktoptas** [comment]
Closed for inactivity. If there is still a bug with the latest release. Please reopen the issue with a screenshot and steps to produce the bug.

**Comment by Fridaythe13thapp** [comment]
@faruktoptas I'm facing the same issue. I'm testing on a Oppo device with a notch and no matter what gravity I set via .titlestyle(R.style.textsyle, Gravity._whatever here_), the title always appears on the top center. 
![Screenshot_2020-03-23-23-08-09-84_b9ce010f083a3a7efe58a6f596c48155](https://user-images.githubusercontent.com/59734501/77344386-3103b700-6d5b-11ea-9aee-2f36c3e43f33.png)
![IMG20200323230650](https://user-images.githubusercontent.com/59734501/77344407-36f99800-6d5b-11ea-9add-3b6e9250ec73.jpg)

**Comment by faruktoptas** [comment]
@Fridaythe13thapp if you want to center it vertically you can try `enableAutoTextPosition()` in your builder.
