### ISSUE TITLE
title text next to the view

### ISSUE THREAD

**Issue by jpainam** [faruktoptas/FancyShowCaseView#159]
Hi, it's not actually an issue
I would like know how to move the text next to the view. 
Gravity.TOP, .CENTER or BOTTOM work but do not do the job.
Maybe we can set the title relative to the position view. 
Thank you for the great lib

**Comment by faruktoptas** [comment]
Hi @jpainam you can set the position manually. Here is an example: https://github.com/faruktoptas/FancyShowCaseView/blob/f03f35c48bcb2bf8896fe1b47ac55e671ca4bac9/app/src/main/java/me/toptas/fancyshowcasesample/MainActivity.kt#L263

You can access focus position and sizes with `calculator.circleCenterX/circleCenter//focusWidth/focusHeight`
But you should take care of small screen size device.

**Comment by jpainam** [comment]
But if I'm not using a custom view. How i can manually position the text? Please in Java.. I'm not familiar with Kotlin

**Comment by faruktoptas** [comment]
You can't do it without using a custom view.
