### ISSUE TITLE
The new version is not supported ConstraintLayout ？

### ISSUE THREAD

**Issue by davidgerka** [faruktoptas/FancyShowCaseView#160]
![image](https://user-images.githubusercontent.com/13624423/65577658-d1447300-dfa6-11e9-9309-44d58461d780.png)
![image](https://user-images.githubusercontent.com/13624423/65577878-46b04380-dfa7-11e9-8db2-edb5f368acd7.png)
![image](https://user-images.githubusercontent.com/13624423/65577931-62b3e500-dfa7-11e9-9562-4ad033af48d4.png)

**Comment by faruktoptas** [comment]
@davidgerka 

I think this is a ConstraintLayout dependency problem. Can you inflate this layout without FancyShowCaseView?

Dou have this dependency in app/build.gradle ?

`implementation 'androidx.constraintlayout:constraintlayout:1.1.3'`

And these lines in gradle.properties

```
android.enableJetifier=true
android.useAndroidX=true
```

**Comment by faruktoptas** [comment]
I couldn't see any problem with ConstraintLayout. If there is a bug. Please reopen the issue with reproduce steps.
