### ISSUE TITLE
Run espresso tests on travis-ci

### ISSUE THREAD

**Issue by faruktoptas** [faruktoptas/FancyShowCaseView#167]
All test cases should be run on each push.

**Comment by faruktoptas** [comment]
Sample .travis.yml file: https://github.com/material-components/material-components-android/blob/master/.travis.yml

**Comment by akhilmaskeri** [comment]
hi, I would like to work on it.
Can you please assign this to me ?

**Comment by faruktoptas** [comment]
Hi @akhilmaskeri you can start working on this task.

**Comment by akhilmaskeri** [comment]
this is something I came up with
```
script:
  ...
   - ./gradlew FancyShowCaseViewTest
```

referencing the sample travis.yml, want to know if
adding -PdisablePreDex flag to a library build makes any performance differences

**Comment by faruktoptas** [comment]
At first we can go on without disabling pre dexing. We may use it later.

**Comment by faruktoptas** [comment]
Closed due to inactivity. Unit tests are used instead of Espresso.
