### ISSUE TITLE
Chaining show case views

### ISSUE THREAD

**Issue by MFlisar** [faruktoptas/FancyShowCaseView#17]
Is this possible? There is no listener for on showcase closed (only for the animation).

Would be nice to have at least a callback which can be setup via the builder

**Comment by faruktoptas** [comment]
It is possible if you set your own enter/exit animations. But if you use default animations it is not possible for now. 
It can be implemented easily. I'm open to contributions :)

**Comment by MFlisar** [comment]
Already done ;-)

**Comment by MFlisar** [comment]
I would make a simple `FancyShowCaseQueue` like following:

    new FancyShowCaseQueue()
        .add(FancyShowCaseView1)
        .add(FancyShowCaseView2)
        .add(FancyShowCaseView3)
        .show();

Internally I would set or wrap the `DismissListener` and show the `FancyShowCaseViews` one after another. Or do you prefer something else?

**Comment by faruktoptas** [comment]
I think this approach is ok. Creating a simple queue will solve this. This is a common usage.

**Comment by MFlisar** [comment]
I'll add this tomorrow to my pull request...
