### ISSUE TITLE
exitAnimation cannot be null

### ISSUE THREAD

**Issue by DanteAndroid** [faruktoptas/FancyShowCaseView#177]
I'd like to disable exit animation but in v1.1.5, `exitAnimation` cannot be set to null.
```
        fun exitAnimation(exitAnimation: Animation): Builder {
            mExitAnimation = exitAnimation
            return this
        }
```
Another problem is, I tried to set `AlphaAnimation` to exitAnimation just to find that, the showCaseView cannot be hidden by `showCaseView.hide()`.

**Comment by faruktoptas** [comment]
Hi @DanteAndroid ,

The new features and bug fixes won't be in non-androidx version. I recommend you to use the latest (androidx) version.
