### ISSUE TITLE
Fragment sequence first showcase not focusing view

### ISSUE THREAD

**Issue by Seeyko** [faruktoptas/FancyShowCaseView#180]
### Screenshot
First view not focusing
![image](https://user-images.githubusercontent.com/26721235/79069226-f099b800-7ccc-11ea-8a92-82bc7b998d51.png)

Second view focusing correctly
![image](https://user-images.githubusercontent.com/26721235/79069234-f8f1f300-7ccc-11ea-89af-e9bbbfaa02b2.png)

### My code
In my fragment onViewCreated i initialize my sequence like this just after creating my two buttons : 
```
        FancyShowCaseView fancyShowCaseView1 = new FancyShowCaseView.Builder(getActivity())
                .title("Found around you by centering your location")
                .focusOn(mCenterLocation)
                .fitSystemWindows(true)
                .build();

        FancyShowCaseView fancyShowCaseView2 = new FancyShowCaseView.Builder(getActivity())
                .title("Add a marker to the map !")
                .focusOn(mAddObject)
                .build();

        mQueue = new FancyShowCaseQueue()
                .add(fancyShowCaseView1)
                .add(fancyShowCaseView2)
       mQueue.show();
```
### Here is my xml file for my two buttons

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/center_location"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:layout_alignParentBottom="true"
        android:layout_marginStart="16dp"
        android:layout_marginLeft="16dp"
        android:layout_marginTop="4dp"
        android:layout_marginEnd="16dp"
        android:layout_marginRight="16dp"
        android:layout_marginBottom="16dp"
        android:scaleType="centerInside"
        android:tint="?attr/colorOnSecondary"
        app:backgroundTint="?attr/colorSecondary"
        app:fabSize="mini"
        app:srcCompat="@drawable/ic_my_location" />

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/add_object"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_above="@id/center_location"
        android:layout_alignParentRight="true"
        android:layout_marginStart="16dp"
        android:layout_marginLeft="16dp"
        android:layout_marginTop="4dp"
        android:layout_marginEnd="16dp"
        android:layout_marginRight="16dp"
        android:layout_marginBottom="4dp"
        android:scaleType="centerInside"
        android:tint="?attr/colorOnSecondary"
        app:backgroundTint="?attr/colorSecondary"
        app:fabSize="mini"
        app:srcCompat="@drawable/ic_add_park" />
</RelativeLayout>

**Comment by faruktoptas** [comment]
@Seeyko I think your views are not laid out when you create the instance.
Can you try to add a delay or use post:
```
mCenterLocation..post(new Runnable() {
            @Override
            public void run() {
                // your code to create FancyShowCaseView
            }
        })
```

**Comment by Seeyko** [comment]
@faruktoptas Thanks for the reply ! It work fine now that i have add a delay.
