### ISSUE TITLE
Circular Background

### ISSUE THREAD

**Issue by abdelrahmanhesham13** [faruktoptas/FancyShowCaseView#182]
Is there anyway to make the background of the fancy show case circular ?

**Comment by faruktoptas** [comment]
Currently it supports fullscreen backgrounds. Or you can create your custom views. Here is an example of custom view:
https://github.com/faruktoptas/FancyShowCaseView/blob/master/app/src/main/java/me/toptas/fancyshowcasesample/MainActivity.kt#L246

**Comment by abdelrahmanhesham13** [comment]
it won't work with custom view animation and circle indicator will not work

**Comment by faruktoptas** [comment]
Why it won't work?

**Comment by abdelrahmanhesham13** [comment]
i need to create circular background while the library provide it own background and animation for circle indicator i try it and it override the library background with no animation and circle indicator

**Comment by faruktoptas** [comment]
You can use a transparent background for FancyShowCaseView
