### ISSUE TITLE
When running on an OS with no status bar or status bar hidden, y value is off

### ISSUE THREAD

**Issue by jeffreyliu8** [faruktoptas/FancyShowCaseView#191]
![Screen Shot 2020-06-11 at 4 00 06 PM](https://user-images.githubusercontent.com/12398645/84447592-3c011180-abfd-11ea-8cc7-175c082a9c2f.png)

**Comment by faruktoptas** [comment]
Please check fitSystemWindows()

https://github.com/faruktoptas/FancyShowCaseView/wiki
