### ISSUE TITLE
How to add margin to title ?

### ISSUE THREAD

**Issue by shahbazhashmi** [faruktoptas/FancyShowCaseView#192]
I am using below style. Everything is working except the margin.

 <style name="ShowcaseTextStyle" parent="Widget.AppCompat.TextView">
        <item name="android:layout_width">wrap_content</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="android:layout_margin">@dimen/spacing_40</item>
        <item name="android:textSize">@dimen/font_22</item>
        <item name="android:textColor">@android:color/white</item>
        <item name="android:fontFamily">@font/montserrat_regular</item>
        <item name="fontFamily">@font/montserrat_regular</item>
    </style>

**Comment by faruktoptas** [comment]
Can you share the full style and your implementation?

**Comment by shahbazhashmi** [comment]
above is the style and below is my implementation

FancyShowCaseView.Builder(activity)
                .focusOn(view)
                .title(text)
                .titleStyle(R.style.ShowcaseTextStyle, gravity)
                .enableAutoTextPosition()
                .build()
                .show()

**Comment by faruktoptas** [comment]
Title style is applying to textAppearance. So you can't set margin with this style. It includes text color, typefaces or text sizes etc. For more details: https://medium.com/androiddevelopers/whats-your-text-s-appearance-f3a1729192d
If you want to set custom margin you should use custom view.

**Comment by shahbazhashmi** [comment]
Okay. But it would be if you can add this feature. I mean it is very common requirement.
