### ISSUE TITLE
How to call the "next" showcaseview?

### ISSUE THREAD

**Issue by XandiVieira** [faruktoptas/FancyShowCaseView#194]
### I'm calling the FancyShowCaseView  in my java code and is displays just fine. I'ts a custom view with a "next" button, so I'd like to open another FancyShowCaseView  for the same screen but nothing happens, the method is triggered but nothing happens, the current FancyShowCaseView   does not close and the new one won't open.

Example:
In Activity onCreate() method I called the code below to show:
java
```
private void callTour() {
        if (Util.getUser().isFirstTime()) {
            new FancyShowCaseView.Builder(this).customView(R.layout.custom_tour_timeline_comment, view -> {
                view.findViewById(R.id.nextStep).setOnClickListener(v -> {
                    callTour2();
                });
            }).focusBorderSize(10)
                    .focusRectAtPosition(100, 500, 2000, 500)
                    .build()
                    .show();
        }
    }
```

```
private void callTour2() {
        if (Util.getUser().isFirstTime()) {
            new FancyShowCaseView.Builder(this).customView(R.layout.custom_tour_timeline_make_comment, view -> {
                view.findViewById(R.id.skip_tutorial).setOnClickListener(v -> {
                });
                view.findViewById(R.id.nextStep).setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        
                    }
                });
            }).focusBorderSize(10)
                    .focusCircleAtPosition(100, 500, 200)
                    .build()
                    .show();
        }
    }
```

### myCustomLayout.xml file 

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1"
        android:orientation="vertical">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:fontFamily="@font/baloo"
            android:gravity="top"
            android:lineSpacingExtra="-15dp"
            android:text="Legal! Este é um assunto bem interessante"
            android:textAlignment="center"
            android:textColor="@color/white"
            android:textSize="@dimen/subtitle"
            tools:ignore="RtlCompat" />

    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1"
        android:orientation="vertical">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:layout_marginHorizontal="10dp"
            android:fontFamily="@font/baloo"
            android:gravity="center_horizontal"
            android:lineSpacingExtra="-5dp"
            android:text="Aqui você pode ver os comentários que já foram feitos sobre este assunto."
            android:textColor="@color/white"
            android:textSize="@dimen/small_text" />

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:layout_marginHorizontal="10dp"
            android:fontFamily="@font/baloo"
            android:gravity="center_horizontal"
            android:lineSpacingExtra="-5dp"
            android:text="Utilize as estrelas para avaliar o comentário."
            android:textColor="@color/colorAccent"
            android:textSize="@dimen/small_text" />

    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:gravity="bottom">

            <TextView
                android:id="@+id/skipTutorial"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="12dp"
                android:layout_marginBottom="7dp"
                android:gravity="bottom"
                android:text="@string/skip_tutorial"
                android:textColor="@color/white"
                android:textStyle="" />
        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:gravity="end">

            <TextView
                android:id="@+id/nextStep"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="5dp"
                android:layout_marginHorizontal="10dp"
                android:padding="10dp"
                android:text="@string/next_step"
                android:textColor="@color/white"
                android:textSize="@dimen/big_text" />
        </LinearLayout>
    </LinearLayout>
</LinearLayout>`

Doesn't it work well with java? I've been struggling to achieve simple stuff such as close the view when a button is hit...

**Comment by Happeal** [comment]
Use FancyShowCaseQueue work fine 😄

**Comment by faruktoptas** [comment]
@XandiVieira you can use FancyShowCaseQueue or your own implementation with custom views. You should check samples:
https://github.com/faruktoptas/FancyShowCaseView/blob/554362401b83baa33290d6471fe8e6815a9f907b/app/src/main/java/me/toptas/fancyshowcasesample/AnimatedActivity.kt#L38

Also you have to call `hide()` method before showing the next one.
