### ISSUE TITLE
Feature request: open API to be able to use circular animation 

### ISSUE THREAD

**Issue by glureau-betclic** [faruktoptas/FancyShowCaseView#195]
Currently the FadeInAnimation and FadeOutAnimation are internal, the doCircularExitAnimation() is private, even the extension circularExitAnimation() is internal. 
Due to that, I can't decide to play a "FadeInAnimation" on the exit, or a "FadeOutAnimation" on the enter.

Want to know if it worth my time to work on it :)

**Comment by faruktoptas** [comment]
These animations are internal animations. Library decides itself to choose one. If you want to use fade animation  you can create your own and use freely. Here is an example: https://github.com/faruktoptas/FancyShowCaseView/wiki/4.-Custom-Enter&Exit-Animations
