### ISSUE TITLE
Adding APK file for the latest release

### ISSUE THREAD

**Issue by faruktoptas** [faruktoptas/FancyShowCaseView#2]

**Comment by Grrlie** [comment]
I'd like to work on this.  Can you tell me if the apk needs to be signed?

**Comment by faruktoptas** [comment]
Yes it should be signed. You can create a keystore file.

**Comment by Grrlie** [comment]
Okay, I added the apk and put in a pull request.  Please let me know if there is something I can improve about the process. I'm completely new to this.

**Comment by harshvardhan-takawale** [comment]
Do I have to make a new keystore?

**Comment by faruktoptas** [comment]
@harshvardhan-takawale yes please. But you should push it too. And add signing config details to build.gradle.

**Comment by harshvardhan-takawale** [comment]
@faruktoptas Sorry for bothering you sir but I am new to open source and as for that matter to android dev as well. I had a small query, what should the keystore path be for this project? Sorry if this is a silly question.

**Comment by faruktoptas** [comment]
@harshvardhan-takawale it is not problem. Don't hesitate to ask questions. I would love to help you for your contribution :)
Keystore file can be in `app` folder.

**Comment by faruktoptas** [comment]
Solved with #53
