### ISSUE TITLE
Overlapping focus view and title

### ISSUE THREAD

**Issue by MFlisar** [faruktoptas/FancyShowCaseView#20]
I think it would make sense to add some logic to avoid this...

The text should be placed in the biggest remaining space on the screen by default imho...

**Comment by faruktoptas** [comment]
You can specify a `GRAVITY` for title with Builder param `titleStyle(@StyleRes int style, int titleGravity)`. But there should be a better way.

**Comment by MFlisar** [comment]
I think, gravity is not enough. I.e. I want to show one text on top (but not overlap my statusbar) and one at the bottom, so I would need to define some padding/margin for this.

I think some smart placement would be really nice, with a logic like following:
* search for the biggest free rectangular space
* center text in this space + allow to define a padding

What do you think about that?

**Comment by faruktoptas** [comment]
Changing the  gravity parameter is a todo in my mind. This approach is ok to me. Due to the device orientation,  title  may be on top, bottom, left and the right side.

**Comment by faruktoptas** [comment]
I think `.enableAutoTextPosition()` solves this. It finds the biggest space vertically and centers in it.
