### ISSUE TITLE
There is a problem with activity switching horizontal screen

### ISSUE THREAD

**Issue by lan2000** [faruktoptas/FancyShowCaseView#206]
### Used FancyShowCaseView version ：1.3.1

Activity needs to achieve horizontal and vertical screen switching. After switching the horizontal screen, there is a problem, as shown in the figure below：

Configure Activity properties:
android:configChanges="orientation|keyboardHidden|screenLayout|screenSize"

### Screenshot if there is something wrong with ui
![image](https://user-images.githubusercontent.com/29618907/91255587-b7ec0e00-e797-11ea-854c-80f80ee6fd33.png)

![image](https://user-images.githubusercontent.com/29618907/91255593-bae6fe80-e797-11ea-9afb-c4a5afe8ba21.png)

**Comment by lan2000** [comment]
There is another question: whether to support the use in Dialogfragment

**Comment by lan2000** [comment]
3.Can you add a new method to set read? When used for multiple prompts, click the function to ignore multiple prompts.

**Comment by faruktoptas** [comment]
@lan2000 I will investigate the orientation problem. It was working but this could be another case.

> There is another question: whether to support the use in Dialogfragment

This is a known issue #184 But PRs welcome :)

> 3.Can you add a new method to set read? When used for multiple prompts, click the function to ignore multiple prompts.

You can use `FancyShowCaseView.isVisible()`static method to see if there is a visible instance.

**Comment by lan2000** [comment]
Can add Skip function similar to MaterialShowcaseView.
For example, if showOnce(id) is enabled, 5 prompts should be displayed.
When it comes to the second one, the user can skip it. Do not prompt again next time.

After the user clicks skip
FancyShowCaseView.isShownBefore(id)==true

**Comment by faruktoptas** [comment]
> Can add Skip function similar to MaterialShowcaseView.
> For example, if showOnce(id) is enabled, 5 prompts should be displayed.
> When it comes to the second one, the user can skip it. Do not prompt again next time.
> 
> After the user clicks skip
> FancyShowCaseView.isShownBefore(id)==true

@lan2000 we can follow this from another issue as an enhancement.
