### ISSUE TITLE
Problem with custom views on ClickListener.

### ISSUE THREAD

**Issue by franquicidad** [faruktoptas/FancyShowCaseView#207]
Hello that you for the atribution to the developer community once I get income from my app I will contribute.
no further due I created the following methods, what I want to do is to guide the user on how to use my app.

`public FancyShowCaseView createShowCaseForCircleImageView(View view, final String title, final String subtitle) {
        mFancyShowCaseView = new FancyShowCaseView.Builder(this)
                .focusOn(view)
                .customView(R.layout.layout_my_custom_view, new OnViewInflateListener() {
                    @Override
                    public void onViewInflated(@NonNull View view) {
                        view.findViewById(R.id.button7).setOnClickListener(new View.OnClickListener() {
                            @Override
                            public void onClick(View view) {
                                mFancyShowCaseView.hide();
                                Fancy2= createShowCaseForSector(textoSeleccionaSector,"Sector","Porfavor recuerda elegir"+
                                        "el sector el cual quieres como preferencia en tu compra");
                                Fancy2.show();
                            }
                        });
                        ((TextView) view.findViewById(R.id.showCaseTitle)).setText(title);
                        ((TextView) view.findViewById(R.id.showCaseDescripcion)).setText(subtitle);
                    }
                })
                .closeOnTouch(false)
                .build();

        return mFancyShowCaseView;
    }
    public FancyShowCaseView createShowCaseForSector(View view, final String title, final String subtitle) {
        Fancy2 = new FancyShowCaseView.Builder(this)
                .focusOn(view)
                .customView(R.layout.layout_my_custom_view, new OnViewInflateListener() {
                    @Override
                    public void onViewInflated(@NonNull View view) {
                        view.findViewById(R.id.button7).setOnClickListener(new View.OnClickListener() {
                            @Override
                            public void onClick(View view) {

                            }
                        });
                        ((TextView) view.findViewById(R.id.showCaseTitle)).setText(title);
                        ((TextView) view.findViewById(R.id.showCaseDescripcion)).setText(subtitle);
                    }
                })

                .closeOnTouch(false)
                .build();
        return mFancyShowCaseView;
    }`

this is an activity so form on create I call the method and its as follows.

`if(showTutorial){
//          FancyShowCaseView fs= createShowCaseForCircleImageView(circleImageView3,"Picture","En lifeOnApp incentivamos" +
//                   "a los asesores comerciales a prestarte el mejor servicio. Sabias que si un \n" +
//                   "asesor comercial con tu imagen recuerda tus intereses y necesidades? es por ello que con tu\n"
//           +"ayuda tendras una mejor atencion y un mejor funcionamiento de LifeOnApp");
//          if(fs!=null) {
//              fs.show();

//          }
            showEnQueue();
        }`

the showEnQueue method is the one I got form wiki. 

But notice I created a button to navigate to the next showCase but the onClick doesn't work on that button.

other question I have is that I can use the enqueue on custom views. and how would it be with the onclick if its not working.

thanks.

**Comment by franquicidad** [comment]
Hello kind sir, I decide to use the showEnQueue method and it is as follows.
`public void showEnQueue(){
        recyclerviewRelacionEscogeEmpresa.setVisibility(View.VISIBLE);
        recyclerSucursal.setVisibility(View.VISIBLE);
        recyclerviewRelacionEscogeEmpresa.setVisibility(View.VISIBLE);

        final FancyShowCaseView fancyShowCaseView1 = new FancyShowCaseView.Builder(this)
                .title("Por favor tomate una foto o seleccionala de tu galeria de telefono")
                .titleGravity(Gravity.BOTTOM)
                .backgroundColor(R.color.colorPrimary)
                .enableAutoTextPosition()
                .focusOn(circleImageView3)
                .build();
        //focusOnView2(nestedScrollView,circleImageView3);


        final FancyShowCaseView fancyShowCaseView2 = new FancyShowCaseView.Builder(this)
                .title("Llena todos tus datos por favor")
                .focusOn(inscripcionNombreClienteOtro)
                .enableAutoTextPosition()

                .backgroundColor(R.color.colorPrimary)
                .build();
                 //focusOnView2(nestedScrollView,inscripcionNombreClienteOtro);



        final FancyShowCaseView fancyShowCaseView3 = new FancyShowCaseView.Builder(this)
                .title("Escoge un Sector en que estes interesado.")
                .backgroundColor(R.color.colorPrimary)
                .enableAutoTextPosition()

                .focusOn(recyclerViewListaSectores)
                .build();
        //focusOnView2(nestedScrollView,recyclerviewRelacionEscogeEmpresa);

        //focusOnView2(nestedScrollView,recyclerViewListaSectores);
        final FancyShowCaseView fancyShowCaseView4 = new FancyShowCaseView.Builder(this)
                .title("Selecciona una sucursal")
                .enableAutoTextPosition()
                .backgroundColor(R.color.colorPrimary)
                .focusOn(recyclerSucursal)
                .build();

        //focusOnView2(nestedScrollView,recyclerSucursal);
        mQueue = new FancyShowCaseQueue()
                .add(fancyShowCaseView1)
                .add(fancyShowCaseView2)
                .add(fancyShowCaseView3)
                .add(fancyShowCaseView4);



        mQueue.show();
    }`

since it is scrollview and has a lot of views in it when i focus on a view that is not on the screen I cant see the focus . Do you have an effective method to travel down to that exact view I've tried this from stack but it doesn't work.

`private final void focusOnView2(NestedScrollView your_scrollview,View view){
        your_scrollview.post(new Runnable() {
            @Override
            public void run() {
                your_scrollview.scrollTo(0, view.getBottom());
            }
        });
    }`

**Comment by faruktoptas** [comment]
Hi @franquicidad 
I think you've missed to use a `dismissListener`. If you use a queue with custom views you have to trigger the queue to show the next one. There is a sample here with custom layout and queue mechanism: https://github.com/faruktoptas/FancyShowCaseView/blob/master/app/src/main/java/me/toptas/fancyshowcasesample/CustomQueueActivity.kt

**Comment by franquicidad** [comment]
> Hi @franquicidad
> I think you've missed to use a `dismissListener`. If you use a queue with custom views you have to trigger the queue to show the next one. There is a sample here with custom layout and queue mechanism: https://github.com/faruktoptas/FancyShowCaseView/blob/master/app/src/main/java/me/toptas/fancyshowcasesample/CustomQueueActivity.kt

Thanks a lot!
