### ISSUE TITLE
Not Possible to Change Focus Size when using .focusShape(FocusShape.ROUNDED_RECTANGLE)

### ISSUE THREAD

**Issue by orentropen** [faruktoptas/FancyShowCaseView#208]
Hello,
I am trying to create a large rectangular focus area. .focusRectAtPosition() allows me to set the size, but only for a rectangle at known coordinates. If I want to use .focusOn(View) in conjunction with .focusShape(FocusShape.ROUNDED_RECTANGLE), there is no function equivalent to .focusCircleRadiusFactor() for rectangles.
I recommend adding a new function, focusRectRadiusFactor(), that can set the scale of a rectangular focus.

**Comment by faruktoptas** [comment]
Hi @orentropen 
This feature does not exist now. If you are interested in contributing. PR's welcome 👍

**Comment by faruktoptas** [comment]
Feature request issue created #212
