### ISSUE TITLE
Add focus size factor for rectangular shape

### ISSUE THREAD

**Issue by faruktoptas** [faruktoptas/FancyShowCaseView#212]
Add `focusRectSizeFactor` parameter for rectangle focus shape (like `focusCircleRadiusFactor` for circular). Default value should be 1.

**Comment by HoussemNasri** [comment]
Is this still open, I wanna work on it

**Comment by faruktoptas** [comment]
@HoussemNasri yes please.

**Comment by Kritip123** [comment]
### @faruktoptas 
I want to contribute to the issue. Could you please explain the issue to me?

**Comment by faruktoptas** [comment]
Hi @Kritip123,

Same implementation is done for circular focus. Please see `focusCircleRadiusFactor`. You will add a new parameter called `focusRectSizeFactor` with 1 default float value. When this value is changed, focused rectangle will be bigger or smaller.

**Comment by kshitij-99** [comment]
@faruktoptas is someone still working on this ? I can fix this.

**Comment by faruktoptas** [comment]
Hi @kshitij-99,

I'm not sure that if @Kritip123 is working on this issue. You can start if his not.

**Comment by kshitij-99** [comment]
@Kritip123 are you working on this ?

**Comment by Kritip123** [comment]
@faruktoptas and @kshitij-99 I was not able to set up the codebase using Android Studio in my system. It was giving some error. So, I could not proceed further. @kshitij-99 you can proceed with the same.

**Comment by kshitij-99** [comment]
That's alright. I will picking this up now with a different account.

**Comment by kshitij-99** [comment]
@faruktoptas opened PR #225. Kindly review and merge.

**Comment by kshitij-99** [comment]
Hey. Did you get a chance to review the PR ?

**Comment by rr-akshay-dave** [comment]
Hi @faruktoptas  Can you please merge above PR and release a new version. Seems lot of folks including myself find this super helpful

**Comment by faruktoptas** [comment]
Released with #225

**Comment by rr-akshay-dave** [comment]
> Released with #225

Thanks a lot!
