### ISSUE TITLE
using closeOnTouch(true),clicking the view multiple times quickly causes problems

### ISSUE THREAD

**Issue by davidgerka** [faruktoptas/FancyShowCaseView#229]
when i using this setting "closeOnTouch(true)", i find a problem : Multiple quick clicks on the view will bring up multiple hidden animations

**Comment by Pozzoooo** [comment]
Got able to reproduce it very clearly at the Sample App by using the "CUSTOM ANIMATION" button.
Gonna investigate.

**Comment by faruktoptas** [comment]
Fixed with #235
