### ISSUE TITLE
Ability to Add custom view above, below and on sides of focused view

### ISSUE THREAD

**Issue by rr-akshay-dave** [faruktoptas/FancyShowCaseView#230]
### Ability to add custom view above, below or on either sides of focused view

Example:
In Activity onCreate() method I use the code below to show:
```kotlin
btn_simple.setOnClickListener {
    FancyShowCaseView.Builder(this)
           .focusShape(FocusShape.ROUNDED_RECTANGLE)
            .enableTouchOnFocusedView(true)
            .customView(R.layout.custom_view_layout, object : OnViewInflateListener {})
            .build()
            .show()
}
```
I am unable to show custom view just above the focused view as there's no easy way to get handle. Trial and error doesn't seem to be working

**Comment by faruktoptas** [comment]
Please check this example: https://github.com/faruktoptas/FancyShowCaseView/blob/efe261a9901938f6e7e23efee726387baf8c789d/app/src/main/java/me/toptas/fancyshowcasesample/MainActivity.kt?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L257

**Comment by rr-akshay-dave** [comment]
@faruktoptas Thanks. I checked it out.
That sample works if a focus view is not dynamic (e.g regular view vs list item view). For focus view that is dynamic the calculations don't always work.

**Comment by faruktoptas** [comment]
Calculations are done when `build()` method is called with a view. If you build your FancyShowCaseView instance after inflation of target view it should work.

**Comment by rr-akshay-dave** [comment]
@faruktoptas Thanks for taking time to respond. I am doing calculations in the `.customView()` method during the build time like below
```
    .customView(R.layout.my_custom_view, object : OnViewInflateListener {
                override fun onViewInflated(view: View) {
                    val params = view.layoutParams as FrameLayout.LayoutParams
                    view.post {
                       // This works
                        params.leftMargin = fancyShowCaseView.focusCenterX - view.width / 2
                        view.layoutParams = params
                    }

                   // some code for init
                      ...
                      ...


                    // Get the layout param of top level view group of custom view
                    val customView = (view as LinearLayout).findViewById<LinearLayout>(R.id.customView)
                    val customViewParamParams = customView.layoutParams as FrameLayout.LayoutParams
                    
                    // Adjust the top margin for custom view so that it's on top of focused view.
                    **_// This DOESN'T WORK._**
                    customViewParams.topMargin =
                        fancyShowCaseView.focusCenterY - fancyShowCaseViewView.focusHeight - focusedView.measuredHeight / 2
                    customView.layoutParams = customViewParams
                }
            })
```

   Let me know if you see something wrong.

**Comment by faruktoptas** [comment]
Can you share a screenshot to see more details about buggy behaviour.

**Comment by rr-akshay-dave** [comment]
Sure.
#### Context Use case 1 : 
* I created list view with 4 textviews in each list item. I am highlighting item # 5 in the list
* I am showing all 4 text views in this case. Notice how custom view is nicely on top
* Screen shot 1: 
![image](https://user-images.githubusercontent.com/69540454/149651323-d9df736a-aa34-45f2-a3b3-86d9b01d7c07.png)

#### Context Use case 1 : 
* I am showing only 2 text views out of 4 text views in this case. Notice how custom view is off
* Screen shot 2: 
![image](https://user-images.githubusercontent.com/69540454/149651399-02414e4c-212b-4570-854e-ca14aa6702c1.png)

**Comment by rr-akshay-dave** [comment]
Btw, I appreciate you taking time to respond. I am happy to DM you on twitter or something to save time for both if that works for you.

**Comment by rr-akshay-dave** [comment]
Hello @faruktoptas , just following up. Let me know if you need anything else on this from my end.

**Comment by DevHisham** [comment]
i faced same issue

**Comment by faruktoptas** [comment]
@rr-akshay-dave @DevHisham 
My apologies for the delayed response. If this is an active issue for you please let me know.
