### ISSUE TITLE
Problem in DialogFragment and BottomSheetDialogFragment

### ISSUE THREAD

**Issue by ligong0904** [faruktoptas/FancyShowCaseView#232]
When the View that needs to be highlighted is located in the DialogFragment or BottomSheetDialogFragment, the CustomView will be displayed in the lower layer of the DialogFragment or BottomSheetDialogFragment, which means that the CustomView is blocked. Can you support the scenario of DialogFragment and BottomSheetDialogFragment?

**Comment by faruktoptas** [comment]
Duplicate of #184

**Comment by andersonguermo** [comment]
[OpenID-Certification-of-Conformance[1].pdf](https://github.com/faruktoptas/FancyShowCaseView/files/13806072/OpenID-Certification-of-Conformance.1.pdf)
