### ISSUE TITLE
Set tiltle function does not work with custom view

### ISSUE THREAD

**Issue by Ashmeeto4s** [faruktoptas/FancyShowCaseView#233]
### Used FancyShowCaseView version 1.3.9
if we provide custom view then title does not show - 

  val fancyShowCaseView1 = FancyShowCaseView.Builder(this)
                .title("First Queue Item")
                .focusOn(btn_queue_1)
                .customView(R.layout.layout_my_custom_view, object : OnViewInflateListener {
                    override fun onViewInflated(view: View) {
                        view.findViewById<View>(R.id.btn_action_1).setOnClickListener(mClickListener)
                    }
                })
                .closeOnTouch(false)
                .dismissListener(dismissListener)
                .build()

**Comment by faruktoptas** [comment]
@Ashmeeto4s It is an intentional design choice. When you customize the view, the responsibility for managing all aspects of the view falls on you.
