### ISSUE TITLE
Focus on landscape has an offset

### ISSUE THREAD

**Issue by Pozzoooo** [faruktoptas/FancyShowCaseView#237]
### Used FancyShowCaseView version
Master

### Screenshot if there is something wrong with ui
![landscape](https://user-images.githubusercontent.com/5278996/175041296-a194fa4a-ee92-43b4-b187-7f0937a22d72.png)

### How you show/hide FancyShowCaseView (in Activity or Fragment, in which method)
Sample app, Rounded Rect button is the easiest to check

I've found that Presenter.getCircleCenter() has adjustment for the status bar, which sounds very sad that it needs to be handled, but it makes me wonder that it might also be needed to handle navigation bar when on landscape?
If that's the case it makes me feel that is a broken behaviour on Android itself, I can't see a reason why either of those offsets should require to be handled at all.

**Comment by Tiarait** [comment]
Hi, try add `.fitSystemWindows(true)`

**Comment by faruktoptas** [comment]
Sorry for late reply. I think @Tiarait's solution solved the your problem @Pozzoooo
