### ISSUE TITLE
Could not get .pom

### ISSUE THREAD

**Issue by jggtelynet** [faruktoptas/FancyShowCaseView#239]
### Used FancyShowCaseView version
1.3.9
### Screenshot if there is something wrong with ui
Could not GET 'https://jitpack.io/com/github/faruktoptas/FancyShowCaseView/1.3.9/FancyShowCaseView-1.3.9.pom'. Received status code 521 from server

I can't download your library..

**Comment by faruktoptas** [comment]
It seems to be a temporary server error from jitapack. It should be working now.
