### ISSUE TITLE
Failed to resolve: me.toptas.fancyshowcase:fancyshowcaseview:1.3.9

### ISSUE THREAD

**Issue by ysnsyhn** [faruktoptas/FancyShowCaseView#243]
Failed to resolve: me.toptas.fancyshowcase:fancyshowcaseview:1.3.9

Are you going to update it ?

 compileSdkVersion = 34
    targetSdkVersion = 34
    buildToolsVersion = "34.0.0"

classpath 'com.android.tools.build:gradle:8.6.1'
distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-all.zip

**Comment by faruktoptas** [comment]
@ysnsyhn Sure i will update it asap.

**Comment by ysnsyhn** [comment]
@faruktoptas Are there any updates?

**Comment by faruktoptas** [comment]
Did you add repository url to your root build.gradle? 

```
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
```

It should still work.

**Comment by faruktoptas** [comment]
@ysnsyhn v1.4.0 is released with target sdk level 34

**Comment by ysnsyhn** [comment]
@faruktoptas  it is already added. I'm still getting the error 
"Failed to resolve: me.toptas.fancyshowcase:fancyshowcaseview:1.4.0"

**Comment by faruktoptas** [comment]
Use this:
`com.github.faruktoptas:FancyShowCaseView:1.4.0` 
not
`me.toptas.fancyshowcase:fancyshowcaseview:1.4.0`
