### ISSUE TITLE
Doesn't work with BottomSheetDialogFragment

### ISSUE THREAD

**Issue by hfahmy** [faruktoptas/FancyShowCaseView#25]
Doesn't work with [BottomSheetDialogFragment](https://developer.android.com/reference/android/support/design/widget/BottomSheetDialogFragment.html). 

The ShowCaseView gets drawn behind the bottom sheet. Any quick workarounds?

**Comment by faruktoptas** [comment]
I'm trying to reproduce it.

**Comment by faruktoptas** [comment]
It seems that BottomSheetDialogFragment creates a new half transparent Activity. So FancyShowCaseView stays on the first activity.

**Comment by hfahmy** [comment]
Yup, that's right. I check the view hierarchy; its a new activity. Anyway to get around this?

**Comment by faruktoptas** [comment]
I think it is `Dialog` behaviour. All dialogs (AlertDialog etc.) appear on top of everything. If you use default BottomSheet implementation (not BottomSheetDialogFragment) it will work. 
Please see https://medium.com/@emrullahluleci/android-bottom-sheet-30284293f066 for implementation.

**Comment by faruktoptas** [comment]
Dialogs are not supported yet because its behaviour.
