### ISSUE TITLE
Wrong position of focus

### ISSUE THREAD

**Issue by vipulasri** [faruktoptas/FancyShowCaseView#30]
Wrong position of focus.

![screenshot_20170406-160145](https://cloud.githubusercontent.com/assets/7822179/24749902/7652dfd0-1ae2-11e7-9e98-d121d8a3e3ea.png)

**Comment by vipulasri** [comment]
this can be solved using `.fitSystemWindows(true)`

**Comment by spencermwatts** [comment]
Thanks, @vipulasri ! How did you find the solution to this?

**Comment by faruktoptas** [comment]
@spencermwatts There is no problem with CoordinatorLayout. If your root layout has `android:fitsSystemWindows="true"` then you need to add `.fitSystemWindows(true)` to `FancyShowCaseView` builder params.
