### ISSUE TITLE
android:allowBackup="true" in library's manifest file

### ISSUE THREAD

**Issue by ForestTree** [faruktoptas/FancyShowCaseView#32]
Please remove this attribute from library's manifest file, it's unusual. This causes a merging error when the application has it set to false.

**Comment by faruktoptas** [comment]
Thank you. I will remove it asap.

**Comment by ForestTree** [comment]
Thank you!

**Comment by faruktoptas** [comment]
Fixed

**Comment by faruktoptas** [comment]
@ForestTree you can use version `0.0.6`. It's just been released :)
