### ISSUE TITLE
FancyShowCaseView with recyclerview item

### ISSUE THREAD

**Issue by vipulasri** [faruktoptas/FancyShowCaseView#33]
How to show FancyShowCaseView with `RecyclerView` item?

**Comment by faruktoptas** [comment]
Get the reference of the view that you want to focus. Then use:
```
new FancyShowCaseView.Builder(YourActivity.this)
    .focusOn(view)
    .title("Focus RecyclerView Items")
    .build()
    .show();
```

**Comment by faruktoptas** [comment]
I added a sample: 
https://github.com/faruktoptas/FancyShowCaseView/blob/dev/app/src/main/java/me/toptas/fancyshowcasesample/RecyclerViewActivity.java

**Comment by thundenilla** [comment]
Hi. How to focus only for the single item of the list ? ie situation: 

Splash screen > dashboard (a list) > auto focus on the first item of the list with show case. ( Right before select the item ) 

Thanks mate !

@faruktoptas
