### ISSUE TITLE
Flag to disable Focus animation

### ISSUE THREAD

**Issue by wengelef** [faruktoptas/FancyShowCaseView#34]
The animation on the focus is nice, but probably more often than not, i don't want that and have 
a static focus instead.
A flag to disable it on the Builder would be nice.

**Comment by faruktoptas** [comment]
Do you mean disabling the focus animation with a parameter in Builder?

**Comment by wengelef** [comment]
yub!

**Comment by faruktoptas** [comment]
You are right. Focus animation should be optional.
