### ISSUE TITLE
Unable to import the library into gradle

### ISSUE THREAD

**Issue by saurabhdhillon** [faruktoptas/FancyShowCaseView#39]
used this in root: 
maven { url 'https://jitpack.io' }

used this in project gradle:
compile 'com.github.faruktoptas:FancyShowCaseView:0.1.0'

**Comment by faruktoptas** [comment]
Did you add maven { url 'https://jitpack.io' } to the project level Gradle or app level Gradle?

**Comment by saurabhdhillon** [comment]
@faruktoptas added it to project level gradle
buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'io.fabric.tools:gradle:1.+'
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4+"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

**Comment by saurabhdhillon** [comment]
Hey @faruktoptas , thanks for the help. 
I got mine corrected by shifting maven { url 'https://jitpack.io' } to
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io"}
    }
}

instead of the previous.

**Comment by faruktoptas** [comment]
You welcome :)

**Comment by Yousha** [comment]
Why not put it in Maven Central or JCenter?

**Comment by faruktoptas** [comment]
@Yousha It is available on JCenter now. 

`implementation 'me.toptas.fancyshowcase:fancyshowcaseview:1.1.4'`

**Comment by faruktoptas** [comment]
@yovi-ep it is available on jitpack.
