### ISSUE TITLE
Add abort/cancel method to FancyShowCaseQueue

### ISSUE THREAD

**Issue by wengelef** [faruktoptas/FancyShowCaseView#41]
I used to call `FancyShowCaseView.hideCurrent(activity)` to hide a whole FancyShowCaseQueue of an Activity.
This doesn't seem to work anymore as it only closes the currently displayed FancyShowCaseView inside the Queue.

Is the current behavior a bug or intended? If it's intended, i think FancyShowCaseQueue should also
have a hideCurrent Method. Or is there already a way to accomplish that?

**Comment by faruktoptas** [comment]
`FancyShowCaseView.hideCurrent(activity)` hides the currently visible `FancyShowCaseView` instance. This is the intended behaviour. 

FancyShowCaseQueue needs an abort/cancel method to stop showing the next `FancyShowCaseView` instance.

**Comment by nagot21** [comment]
@wengelef, you can emulate this function by inserting all FancyShowCaseView you've got in a List. Then just create an cancel button that will call FancyShowCaseView.hide() and then clear your List.

Also keep in mind that if you are emulating FancyShowCaseQueue behavior with a List you have to use a handler to give some delay between transitions otherwise it won't work.

**Comment by wengelef** [comment]
@nagot21 thanks i'm aware of that. I don't really want to emulate anything and this sounds like smelly code to me.

Maybe i will have time at the weekend to file a PR, it it isn't already in progress.

**Comment by nagot21** [comment]
@wengelef 

Yes, I think it's in progress. But if have just can't wait for an update that's the only solution so far =/
I hope this new function is available in the next release.

**Comment by faruktoptas** [comment]
It's not in progress. I haven't started yet.

**Comment by faruktoptas** [comment]
@nagot21 do you need this feature urgently?

**Comment by nagot21** [comment]
@faruktoptas 
Would be nice if you could but no pressure at all! As I said before I kinda made an workaround to make it work.
