### ISSUE TITLE
how to show in fragment ?

### ISSUE THREAD

**Issue by lanetteamtapan** [faruktoptas/FancyShowCaseView#42]
i checked the code it seems library is finding views from an activity only . how can i display in fragment ?

**Comment by faruktoptas** [comment]
You can use in fragments. Just use `new FancyShowCaseView.Builder(getActivity())`

**Comment by gsy450896356** [comment]
The location in the fragment is not correct, higher than the normal position

**Comment by faruktoptas** [comment]
If your root layout has `android:fitsSystemWindows="true"` then you need to add `.fitSystemWindows(true)` to `FancyShowCaseView` builder params.

**Comment by gsy450896356** [comment]
Thanks
