### ISSUE TITLE
Prevent too big focus views to overflow screen

### ISSUE THREAD

**Issue by faruktoptas** [faruktoptas/FancyShowCaseView#44]

**Comment by Anirudh257** [comment]
Hey, I think I can work on this issue

**Comment by faruktoptas** [comment]
Ok. This issue is assigned to you. Thanks

**Comment by Walikdik** [comment]
Can I start working on this please?

**Comment by faruktoptas** [comment]
@Walikdik Sure you can start.

**Comment by faruktoptas** [comment]
I think this is not needed any more.
