### ISSUE TITLE
Views that are not on focus on .closeOnTouch(false) are still clickable

### ISSUE THREAD

**Issue by nagot21** [faruktoptas/FancyShowCaseView#45]
Heya,

I've notice that when you are using a view as a focus with closeOnTouch set as false the other views, for instance a button, below the overlay are still clickable.

Is there a way to go around it?

Cheers!

**Comment by faruktoptas** [comment]
Hi,

If you set `closeOnTouch(false)` it will be `setClickable(false)`. So below overlay is still clickable. 
It should be `setClickable(true)` by default. And `closeOnTouch` should assign a `null` click listener. 

I will fix asap with the next release

Thanks

**Comment by Perick95** [comment]
Hi,

I have the same problem, if I set closeOnTouch (false) and enableTouchOnFocusedView (true) the other things below the overlay are still clickable.
Another issue is if I touch the view on focus the overlay doesn't hide.
 
Is there a way to do these two things?

Thank you!

**Comment by faruktoptas** [comment]
@Perick95 closeOnTouch(false) prevents closing when touch. So closing is your responsibility. 
enableTouchOnFocusedView(true) makes the focused view touchable. This is the behaviour. 

Is there still a problem?
