### ISSUE TITLE
FancyShowCaseView.Builder.build() method performance

### ISSUE THREAD

**Issue by gemiren** [faruktoptas/FancyShowCaseView#48]
First of all, thanks for this awesome library. Here is a small performance enhancement request. The builder should check whether it has been shown before if showOnce flag is set and do thing if it has been shown before. No need to continue building the view in this case. Thanks.

**Comment by faruktoptas** [comment]
Thanks @gemiren 
You are right. I will do this enhancement.

**Comment by ncondron42** [comment]
I can think of a few ways of optimizing this scenario:

1. when showOnce(id) is called, check if the flag is already set to true for that id and if so, return a dummy subclass of Builder that only returns itself for each function
2. Add a check to each builder function that checks for the flag and if set do nothing.
3. When build() is called, check the flag and if set to true for mId create a FancyShowCaseView using a new alternate constructor that avoids all the work (calls to show() will result in nothing)

None strike me as very useful optimizations. Is there another way of implementing this?

**Comment by faruktoptas** [comment]
Thanks @ncondron42 for your contribution.
I monitored process times and see that longest process is showing the view. Setting builder params and `build()` method doesn't take too much time. Using an alternate constructor takes same time as the real constructor.
So this optimisation is not necessary.
