### ISSUE TITLE
Listener on complete of ShowCase Queue

### ISSUE THREAD

**Issue by sundeepkmallick** [faruktoptas/FancyShowCaseView#49]
Hi @faruktoptas, 

It would be great if you can provide listener on complete of ShowCase Queue like below:

`FancyShowCaseQueue fq = new FancyShowCaseQueue()
                .add(fancyShowCaseView1)
                .add(fancyShowCaseView2)
                .add(fancyShowCaseView3)
                .add(fancyShowCaseView4)
                .show();

        fq.setOnCompleteListener(new OnCompleteListener() {
            @Override
            public void onComplete() {
                //Queue completed
            }
        });`

**Comment by harshvardhan-takawale** [comment]
I am new to open source development and wish to take up this task if you permit. Any help would be appreciated.

**Comment by faruktoptas** [comment]
Thank you @harshvardhan-takawale of course you can contribute to this repository. You can choose one from the issues below:
#2 - Adding an apk for the sample app
#11 - Updating README.md to explain all builder methods
#48  - FancyShowCaseView.Builder.build() method performance

I can help you if you need help.

**Comment by faruktoptas** [comment]
Closed with #50
