### ISSUE TITLE
Bottom bar items are not getting focused 

### ISSUE THREAD

**Issue by ZahraHeydari** [faruktoptas/FancyShowCaseView#54]
I used it like this:
-=-=-=-=-=-=-=-
new FancyShowCaseView.Builder(this)
                .focusOn(findViewById(R.id.tab_home))
                .title("Focus on View")
                .focusShape(FocusShape.CIRCLE)
                .build()
                .show();

**Comment by faruktoptas** [comment]
Are you trying to show in `onCreate()` ? Try to show `FancyShowCaseView` with 100ms delay. You can use `view.postDelayed()`.

**Comment by ZahraHeydari** [comment]
Yes,I called it in onCreate() but it covers all screen and doesn`t get focus on Tab!

**Comment by faruktoptas** [comment]
view.postDelayed() will solve it.

**Comment by ZahraHeydari** [comment]
Thanks,it solved my problem.

**Comment by faruktoptas** [comment]
You welcome.

If you have an an app in Google Play Store that use FancyShowCaseView let me know and I will add your app to the list of [apps that use this library](https://github.com/faruktoptas/FancyShowCaseView#already-in-use-in-following-apps) in README.
