### ISSUE TITLE
removeView() not called when custom exit animation applied

### ISSUE THREAD

**Issue by Jeevuz** [faruktoptas/FancyShowCaseView#56]
Hi, thanks for the library! 
I think it should call removeView() when custom exit animation set, isn't it?

**Comment by faruktoptas** [comment]
You welcome @Jeevuz 
`removView` is not automatically called by the library. You can do it manually. I left it to user's responsibility. If you set custom exit animation you may want to do something else when animation ends. That's the reason.

**Comment by Jeevuz** [comment]
This is the reason I was thinking about. Makes sense. Thank you for clarification!
