### ISSUE TITLE
How to skip all show case views?

### ISSUE THREAD

**Issue by ZahraHeydari** [faruktoptas/FancyShowCaseView#59]
How can I apply the skipping action to skip all show case views when I use FancyShowCaseQueue?

**Comment by faruktoptas** [comment]
@ZahraHeydari `FancyShowCaseQueue` has a `cancel` method. You can use it.

**Comment by ZahraHeydari** [comment]
Can I call it when my first view of queue is displayed?

**Comment by faruktoptas** [comment]
Yes you can call.

**Comment by ZahraHeydari** [comment]
Well how can I detect a view was displayed to do it?

**Comment by faruktoptas** [comment]
You can use `FancyShowCaseView.isVisible(activity)` static method to check that if a `FancyShowCaseView` is on screen.

**Comment by ZahraHeydari** [comment]
okay.I got it.Thanks
