### ISSUE TITLE
How to change the font family of the title ?  

### ISSUE THREAD

**Issue by Janipasha** [faruktoptas/FancyShowCaseView#60]
What is the font used in the title ? How can I change it ?

**Comment by faruktoptas** [comment]
You can use a style with `titleStyle()` builder method to change the font. 

Here is the example:
https://github.com/faruktoptas/FancyShowCaseView/blob/master/app/src/main/java/me/toptas/fancyshowcasesample/MainActivity.java#L134

**Comment by Janipasha** [comment]
I am using calligraphy font library , Creating a style file doesn't work
with it

**Comment by faruktoptas** [comment]
You can use styles with Calligraphy.

```
<style name="MyCustomFont">
    <item name="fontPath">fonts/MyFont.otf</item>
</style>
```

**Comment by falkontre** [comment]
I tested the solution via style and font is not loaded (with Calligraphy)
