### ISSUE TITLE
Adding new shapes

### ISSUE THREAD

**Issue by ncondron42** [faruktoptas/FancyShowCaseView#62]
What do you think about adding new shapes besides circle and rounded rectangle? The code reads as though rounded rectangle was added as an afterthought. Thinking about generalizing the code and supporting a couple more shapes (elipse, rectangle).

**Comment by faruktoptas** [comment]
Focus shape can be abstracted. So custom shapes can be implemented. But I've to change the focus canvas approach.

**Comment by faruktoptas** [comment]
Not planned to be added. PR's welcome :)
