### ISSUE TITLE
Title position is wrong

### ISSUE THREAD

**Issue by msecilmis** [faruktoptas/FancyShowCaseView#63]
```
new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                new FancyShowCaseView.Builder(getmActivity())
                        .focusOn(btnTwitterLogin)
                        .title("Etc etc")
                        .focusShape(FocusShape.ROUNDED_RECTANGLE)
                        .fitSystemWindows(true)
                        .titleSize(20, TypedValue.COMPLEX_UNIT_SP)
                        .titleStyle(0, Gravity.TOP | Gravity.CENTER_HORIZONTAL)
                        .build()
                        .show();
                sharedPrefManager.setIsLoginFragmmentAnimationsSeen(true);
            }
        }, 100);
```
First, in this code snippet (when i use titleStyle(...) ) fistsystemwindows(true) has no effect.

I tried to use titleGravity(..) with fitSystemWindows(true), in that case the title gets pushed outside the screen partially. I thought i could solve it by defining a style with marginTop and apply it and then the fitSystemWindows is eliminated and the button's focus is pushed upwards. :)

Any idea? Btw love the library.

**Comment by faruktoptas** [comment]
Thanks @msecilmis 

Can you share a screenshot?
fitSystemWindows(true) must be used if your root view has fitSystemWindows=true parameter. It's not about title.

**Comment by msecilmis** [comment]
Yeah, i know fitSystemWindow is not about the title. What I'm saying is that using titleStyle eliminates the effect of fitSystemWindows.

![screenshot_20170803-120333 1](https://user-images.githubusercontent.com/15646492/28914336-f9cc88e8-7843-11e7-9627-fe0a3372e50a.png)

**Comment by faruktoptas** [comment]
Interesting. I've tried the same code. But it works for me. Can you share your layout xml file?

Also you don't need ` sharedPrefManager.setIsLoginFragmmentAnimationsSeen(true);` 
Just adding `showOnce(id)` to builder params is enough. 
And with the version 0.1.3 showing in postDelayed method is not needed.

**Comment by msecilmis** [comment]
Actually in the above case, my layout didnt have fitSystemWindows(true) so that was the problem, i got it working now. But in your sample app, in SecondActivity, if you try to set titleGravity(Gravity.TOP), I'm pretty sure you can reproduce my problem. Btw I'm using the showcase in a fragment, that's the reason that I'm pretty sure not completely.

**Comment by msecilmis** [comment]
i.e.

new FancyShowCaseView.Builder(getmActivity())
                .focusOn(btnFourth)
                .title("etc etc")
                .fitSystemWindows(true)
                .titleStyle(0, Gravity.TOP)
                .titleSize(20, TypedValue.COMPLEX_UNIT_SP)
                .focusShape(FocusShape.ROUNDED_RECTANGLE)
                .build().show();

gives me:

![screenshot_20170803-140447](https://user-images.githubusercontent.com/15646492/28919400-fcd6baec-7855-11e7-822b-dd2ef77c145b.png)


and my fragment is inside the MainActivity that has the DrawerLayout that has the attribute     android:fitsSystemWindows="true"

**Comment by msecilmis** [comment]
EDIT: I cloned your repository and ;

```
 @OnClick(R.id.button1)
    public void focus() {
        if (!isFinishing()) {
            new FancyShowCaseView.Builder(SecondActivity.this)
                    .focusOn(mButton)
                    .title("Focus a view")
                    .fitSystemWindows(true)
                    .titleStyle(0, Gravity.TOP)
                    .build()
                    .show();
        }
    }
```

gives me:

![screenshot_20170803-142205 2](https://user-images.githubusercontent.com/15646492/28919671-35d1ba58-7857-11e7-9fe0-10a9ba14f968.png)

**Comment by faruktoptas** [comment]
Yes I reproduced it. Title overflows the screen. I've found out the problem. Setting a style with margin can be used as a workaround.
But I will fix it :)

**Comment by msecilmis** [comment]
Actually to leave this as a note, style with a margin doesn't work since it vanishes the effect of fitSystemWindow(true) . So we should wait for you to fix it, there are no workaround that i can think of.

**Comment by msecilmis** [comment]
With more fiddling, I found a workaround:

Just make a custom layout with a textview with a margin and that's it.

**Comment by NoHarmDan** [comment]
Could you please elaborate on the custom layout and margin? Because I have this problem with a custom layout I need to use (changing the fitSystemWindow parameter only makes it worse, regardless of its setting in the layout) and I can't figure the workaround out...

**Comment by Happeal** [comment]
I have the same problem here :

FancyShowCaseView.Builder(activity)
            .fitSystemWindows(true)
            .focusOn(focus)
            .focusBorderColor(activity.resources.getColor(R.color.colorPrimary))
            .disableFocusAnimation()
            .titleSize(19, TypedValue.COMPLEX_UNIT_DIP)
            .title(activity.getString(text))

**Comment by faruktoptas** [comment]
@Happeal can you share a screenshot please?
