### ISSUE TITLE
change animation radius (mAnimCounter)

### ISSUE THREAD

**Issue by k1p7** [faruktoptas/FancyShowCaseView#69]
Hello.
Can you add function to change animation radius? Or, just set public construction to your classes?
Thank you for lib

**Comment by faruktoptas** [comment]
@k1p7 Sorry for late reply. You want to set `ANIM_COUNTER_MAX` value not `mAnimCounter`. Its value is 20 by default now. I will add a builder param to set max value for `mAnimCounter`.
