### ISSUE TITLE
Accessing mContainer view via mFancyShowCaseView.getView() method

### ISSUE THREAD

**Issue by faruktoptas** [faruktoptas/FancyShowCaseView#7]

**Comment by eanurag** [comment]
`mFancyShowCaseView.getView()` is supposed to return `mView`, which is the view to focus. `mContainer` is the FrameLayout used for FancyShowCaseView. Why would you want to access `mContainer` from `mView` ?

**Comment by faruktoptas** [comment]
You are right. `mFancyShowCaseView.getContainerView()` would be better.
