### ISSUE TITLE
Looping with custom animation

### ISSUE THREAD

**Issue by Lex74** [faruktoptas/FancyShowCaseView#71]
Hello! The library is great, but there is an error. I want to set your fade animation for every api version. I use this code to create an animation:
Animation animationOut = AnimationUtils.loadAnimation(this, R.anim.fscv_fade_out);
And then in the builder:
.exitAnimation(animationOut)

Now, if I tap the show case view, it appears again and again

**Comment by Lex74** [comment]
Looks like, you have to use onAnimationEnd() with removeView() for custom animation

**Comment by faruktoptas** [comment]
Yes you need to call `removeView()` in `onAnimationEnd()` method. Please see the [wiki](https://github.com/faruktoptas/FancyShowCaseView/wiki/4.-Custom-Enter&Exit-Animations)
