### ISSUE TITLE
Graphics problem when rotating screen

### ISSUE THREAD

**Issue by Spettacolo83** [faruktoptas/FancyShowCaseView#72]
Thank you for this amazing repository!
I've noticed some problem after rotating screen:
- wrong background 
- wrong circle position
How can I fix it?
Cheers!

**Comment by faruktoptas** [comment]
Thank you @Spettacolo83 
I will check the problem asap.

**Comment by faruktoptas** [comment]
@Spettacolo83 can you share a screenshot. I works well with landscape too.

**Comment by Spettacolo83** [comment]
I prevented the landscape because of this bug at the moment.

**Comment by faruktoptas** [comment]
Can you enable landscape and share screenshot with me?

**Comment by Spettacolo83** [comment]
Hi @faruktoptas 
this is an example...

![landscape_fancy](https://user-images.githubusercontent.com/5663188/31940228-4572302a-b8b5-11e7-9cd0-4036bd600847.jpg)

As you can see, my layout is resized but the black background doesn't.
Thank you!

**Comment by faruktoptas** [comment]
Closed due to inactivity.
