### ISSUE TITLE
Circular enter reveal not working because getWidth/getHeight return 0

### ISSUE THREAD

**Issue by efung** [faruktoptas/FancyShowCaseView#74]
I'm using a custom overlay view, with a circular focus on a FAB, testing on an API 26 device.  I'm trying to debug why the circular enter animation wasn't working (but the exit one is fine). I've tried calling `FancyShowCaseView.show()` in `onStart` and `onResume`. I can see that the animation start code is the `onPreDraw` callback of the showcase view's view tree observer, so the showcase view should be measured already.

But, for whatever reason, the `getWidth` and `getHeight` methods are returning 0.

Since the overlay is full-screen, instead of getting the width/height of the overlay [here]( https://github.com/faruktoptas/FancyShowCaseView/blob/master/library/src/main/java/me/toptas/fancyshowcase/FancyShowCaseView.java#L417), could you instead just get the device width and height?

**Comment by faruktoptas** [comment]
@efung can you share your layout xml file?

**Comment by efung** [comment]
Hmm, on further experimentation today, it happens in one of my activities but not another. I think there's some kind of threading issue, perhaps related to RxJava.

I'll report back here when I figure it out.

**Comment by faruktoptas** [comment]
Ok let me know if there is a problem.

**Comment by efung** [comment]
Still have not figured it out. I've built your sample on my device, and it works fine. I added a FAB to `SecondActivity` and focused on it, using a custom view, to replicate my layout, and it's fine.

For what it's worth, in my app, we're using Kotlin and the Kotlin Android Extensions.

**Comment by efung** [comment]
I've been able to reproduce the problem. In my PR, the first commit modifies one of the activities in the sample app to demonstrate the problem. 

When you click `ANOTHER ACTIVITY`, you get taken to the second activity, and the focus shows on one of the buttons. However, if you change the code to create the showcase view explicitly, rather than calling `performClick` on the focused button, **the enter animation does not run**.
