### ISSUE TITLE
Focus on AlertDialog

### ISSUE THREAD

**Issue by visherandro** [faruktoptas/FancyShowCaseView#79]
How to make it work on alert dialog

**Comment by faruktoptas** [comment]
@visherandro 
Dialogs are shown on top of other views. So dialogs are not supported yet.

**Comment by djsbaa** [comment]
You can customize your dialog and add it setOnShowListener()

**Comment by supasheva** [comment]
Hi. Has this issue been resolved finally?

**Comment by faruktoptas** [comment]
@supasheva good news :)
Can you create a PR please?

**Comment by faruktoptas** [comment]
@supasheva Unfortunately not yet.

**Comment by faruktoptas** [comment]
Closed due to inactivity.
