### ISSUE TITLE
Accessing focus circle position and radius parameters (x, y, r)

### ISSUE THREAD

**Issue by faruktoptas** [faruktoptas/FancyShowCaseView#8]
Public `getFocusPosition()` and `getFocusRadius()` that should be defined

**Comment by kratikagoyel** [comment]
I believe that these public methods need to be added to /library/src/main/java/me/toptas/fancyshowcase/FancyShowCaseView.java. Kindly correct me if I am wrong.

**Comment by faruktoptas** [comment]
@kratikagoyel Yes you are right. But I think there should be a method named `hasFocus()` Because focus view is not mandatory. And don't forget to get the latest version of source. I've just released `0.0.4`

**Comment by kratikagoyel** [comment]
@faruktoptas I will pick it up, kindly assign the issue to me.

**Comment by faruktoptas** [comment]
Thanks @kratikagoyel 
Creating a pull request is enough. Please don't forget to push your commits to `dev` branch.

**Comment by faruktoptas** [comment]
Pleas don't forget rounded rectangle shape. It doesn't have a radius.

**Comment by kratikagoyel** [comment]
@faruktoptas What should the behavior of `getRadius()` (and the functions for accessing `centerX` & `centerY`)  in case of rounded rectangle shape. Should we return -1 if the focus shape is `ROUNDED_RECTANGLE` ?

**Comment by faruktoptas** [comment]
For Circle:
* `mCenterX`
* `mCenterY`
* `mRadius`
* `mWidth`
* `mHeight`
* `mTop`
* `mLeft`

For Rounded Rect:
* `mCenterX`
* `mCenterY`
* `mWidth`
* `mHeight`
* `mTop`
* `mLeft` 
* `mRadius` should return -1

**Comment by faruktoptas** [comment]
@kratikagoyel are you working on this issue? @turbolay created a pull request for this.

**Comment by turbolay** [comment]
I saw the the issue hadn't move during 8 days so I imagined nobody was working for this! Hope it was the case!
