### ISSUE TITLE
how to disable enterAnimation and ExitAnimation ?

### ISSUE THREAD

**Issue by akshayISTAR** [faruktoptas/FancyShowCaseView#80]

**Comment by faruktoptas** [comment]
@akshayISTAR You can customize enter/exit animations. Create an animation with 0 duration then set it.

https://github.com/faruktoptas/FancyShowCaseView/wiki/4.-Custom-Enter&Exit-Animations

**Comment by akshayISTAR** [comment]
Thank you. I found a sightly different solution. I made an empty file in 'anim' directory named 'falseAnim.xml' file and set it in enterAnimation and exitAnimation of my fancyShowCaseView object to disable enterAnimation and exitAnimation.
