### ISSUE TITLE
No focus on Toolbar Menu item

### ISSUE THREAD

**Issue by felixeduardo15** [faruktoptas/FancyShowCaseView#81]
```
new FancyShowCaseView.Builder(this)
                .focusOn(menu)
                .focusShape(FocusShape.ROUNDED_RECTANGLE)
                .title(getString(R.string.add_phone))
                .titleGravity(1)
                .build().show();
```

`View menu = findViewById(R.id.locations);` //R.id.locations = menu id

**Comment by SpencerDepas** [comment]
I would also like this feature.

**Comment by faruktoptas** [comment]
It works well with ToolBar menu items. Here is the example:

https://github.com/faruktoptas/FancyShowCaseView/blob/master/app/src/main/java/me/toptas/fancyshowcasesample/SecondActivity.java

```java
@Override
public boolean onOptionsItemSelected(MenuItem item) {
    new FancyShowCaseView.Builder(this)
            .focusOn(findViewById(item.getItemId()))
            .title("Focus on Actionbar items")
            .fitSystemWindows(true)
            .build()
            .show();
    return true;
}
```

**Comment by SpencerDepas** [comment]
Thank you.

**Comment by prasad456** [comment]
Its showing only on click, I have to display in queue

**Comment by Happeal** [comment]
I agree I need to focus on the three dot menu not on a specific item ( I just have an actionbar without toolbar.getView() )

**Comment by Happeal** [comment]
I agree I need to focus on the three dot menu not on a specific item ( I just have an actionbar without toolbar.getView() )

I face this error :
```
 java.lang.IllegalStateException: findViewById(R.id.action_change_booking) must not be null
        at UpcomingRideActivity.onCreateOptionsMenu(UpcomingRideActivity.kt:181)
```

with this code : 
```
  override fun onCreateOptionsMenu(menu: Menu?): Boolean {
        menuInflater.inflate(R.menu.menu_upcoming_ride, menu)

        TutorialManager.explainRideAssistance(this, findViewById(R.id.action_change_booking))?.let {
            TutorialManager.addToQueue(it)
        }
`

**Comment by faruktoptas** [comment]
@Happeal As you see in the trace view is null. Because you are trying to access view in onCreateOptionsMenu(). I think the view is not laid out yet.
