### ISSUE TITLE
Not focusing properly on item

### ISSUE THREAD

**Issue by Deeptimay** [faruktoptas/FancyShowCaseView#82]
this how it's focusing in my app. What should i do ?

![screenshot_1513068050](https://user-images.githubusercontent.com/11171478/33874983-ba999764-df46-11e7-8bb8-60eaba5cf29a.png)

**Comment by faruktoptas** [comment]
https://github.com/faruktoptas/FancyShowCaseView/wiki

NOTE: .fitSystemWindows(true) MUST be added to builder parameters if your root view has android:fitsSystemWindows="true"

**Comment by Deeptimay** [comment]
It worked thanks. @faruktoptas
