### ISSUE TITLE
Using your library

### ISSUE THREAD

**Issue by Alikaraki95** [faruktoptas/FancyShowCaseView#84]
Hey,
couldn't find another way to tell ya, but thanks for the awesome library:) I just wanted to say that i'm using it now and already included it's name in my app. In case you want to add it to the README, [Here is the link to mine](https://play.google.com/store/apps/details?id=com.nephi.getoffyourphone)

Cheers mate!

**Comment by faruktoptas** [comment]
Thanks @Alikaraki95 you can make a pull request and add your app to README.md
