### ISSUE TITLE
I can't pointing to Action bar Menu item 

### ISSUE THREAD

**Issue by asqa** [faruktoptas/FancyShowCaseView#85]
when I try to target an action bar menu item and put the code inside onOptionsItemSelected then show case view will displayed after i click right? but i want show case view displayed first time when i open that page.. how i can fix it?

**Comment by faruktoptas** [comment]
@asqa You can do it in onCreateOptionsMenu() method. But a handler is needed because menu item view is not inflated yet when this method triggers. Here is the code:

```java
@Override
public boolean onCreateOptionsMenu(Menu menu) {
    getMenuInflater().inflate(R.menu.menu_main, menu);
    new Handler().postDelayed(
            new Runnable() {
                @Override
                public void run() {
                    new FancyShowCaseView.Builder(MainActivity.this)
                            .focusOn(findViewById(R.id.item_1)) // ActionBar menu item id
                            .title("Focus on Actionbar items")
                            .build()
                            .show();
                }
            }, 50
    );
    return super.onCreateOptionsMenu(menu);
}
```

**Comment by asqa** [comment]
Thanks for solution, now i got another error,,when i try to remove showcase with button my app getting force close.. here is my code :

public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_contact, menu);

        new Handler().postDelayed(
                new Runnable() {
                    @Override
                    public void run() {
                        new FancyShowCaseView.Builder(ContactTabActivity.this)
                                .focusOn(findViewById(R.id.item_sync)) // ActionBar menu item id
                                .focusCircleRadiusFactor(1.5)
                                .customView(R.layout.case_view_sync, new OnViewInflateListener() {
                                    @Override
                                    public void onViewInflated(@NonNull View view) {
                                        view.findViewById(R.id.btnOke).setOnClickListener(new View.OnClickListener() {
                                            @Override
                                            public void onClick(View view) {
                                                mFancyShowCaseView.removeView(); // this doesn't work
                                            }
                                        });
                                    }
                                }).closeOnTouch(true)
                                .build()
                                .show();
                    }
                }, 50
        );
        return super.onCreateOptionsMenu(menu);

    }

**Comment by faruktoptas** [comment]
Because mFancyShowCaseView is null.

You should do this:

`mFancyShowCaseView = new FancyShowCaseView.Builder(ContactTabActivity.this)`

**Comment by asqa** [comment]
So create an object first before mFancyShowCaseView. removeView();

**Comment by faruktoptas** [comment]
No. Your code shuld be:

```
new Handler().postDelayed(
            new Runnable() {
                @Override
                public void run() {
                    mFancyShowCaseView = new FancyShowCaseView.Builder(ContactTabActivity.this)
                            .focusOn(findViewById(R.id.item_sync)) // ActionBar menu item id
                            .focusCircleRadiusFactor(1.5)
                            .customView(R.layout.case_view_sync, new OnViewInflateListener() {
                                @Override
                                public void onViewInflated(@NonNull View view) {
                                    view.findViewById(R.id.btnOke).setOnClickListener(new View.OnClickListener() {
                                        @Override
                                        public void onClick(View view) {
                                            mFancyShowCaseView.removeView(); // this doesn't work
                                        }
                                    });
                                }
                            }).closeOnTouch(true)
                            .build()
                            .show();
                }
            }, 50
    );
    return super.onCreateOptionsMenu(menu);

}
```
