### ISSUE TITLE
please help me，the focus view is show this，the location is wrong。

### ISSUE THREAD

**Issue by YanxuLi** [faruktoptas/FancyShowCaseView#86]
![screenshot_2018-02-11-17-28-09-41](https://user-images.githubusercontent.com/17410522/36071923-7bba77fa-0f0e-11e8-98ae-1e6a03f25c14.png)
![screenshot_2018-02-11-17-28-04-86](https://user-images.githubusercontent.com/17410522/36071924-7beb6338-0f0e-11e8-9149-10a44beed961.png)

**Comment by YanxuLi** [comment]
I know the problem，because the Theme ，in other words，is the StatusBar，I changed the theme to android:theme="@style/Theme.Design.Light.NoActionBar，it worked。
![screenshot_2018-02-11-17-52-07-28](https://user-images.githubusercontent.com/17410522/36072088-694b1284-0f11-11e8-9831-747546958b2f.png)

Can you think about this situation and push updates?

**Comment by faruktoptas** [comment]
Is your root view has android:fitSystemWindiws="true"?

**Comment by YanxuLi** [comment]
sorry，I saw this attribute later.now it's workd,thank you~
