### ISSUE TITLE
Custom View without custom TextView

### ISSUE THREAD

**Issue by TheJordisc** [faruktoptas/FancyShowCaseView#87]
Is there any way to use a custom view for just adding a button? I tried to use that feature but it seems to be mandatory to put a TextView in my custom view in order to see any text.

I want to use a custom view to add an exit button, but i got too many showcase views to use a custom layout for each string. And setting the strings and positioning the TextView programatically at every showcase queue step would be very tedious (I don't know if this would be even possible with queues). I'd like to use a custom view combined with the .title() and .titleStyle() methods.

Thanks!

**Comment by faruktoptas** [comment]
@TheJordisc You can't use .title() and titleStyle() methods with custom view. But you can do it easily with the method below:

```java
public FancyShowCaseView createShowCase(View view, String id, final String title, final String subtitle) {
        mFancyShowCaseView = new FancyShowCaseView.Builder(this)
                .focusOn(view)
                .customView(R.layout.layout_my_custom_view, new OnViewInflateListener() {
                    @Override
                    public void onViewInflated(@NonNull View view) {
                        view.findViewById(R.id.btn_action_1).setOnClickListener(mClickListener);
                        ((TextView) view.findViewById(R.id.item_1)).setText(title);
                        ((TextView) view.findViewById(R.id.item_2)).setText(subtitle);
                    }
                })
                .showOnce(id)
                .closeOnTouch(false)
                .build();
        return mFancyShowCaseView;
    }
```
