### ISSUE TITLE
android-apt deprecated

### ISSUE THREAD

**Issue by 97balakrishnan** [faruktoptas/FancyShowCaseView#88]
android-apt got deprecated with android studio version 2.2 and the Gradle files have to be updated to support android studio developers.

**Comment by faruktoptas** [comment]
@97balakrishnan do you want to make a PR?

**Comment by 97balakrishnan** [comment]
Yes . I have started working on it.

**Comment by 97balakrishnan** [comment]
I am getting some error in Travis cl can you help?
