### ISSUE TITLE
Adding robolectric unit tests

### ISSUE THREAD

**Issue by faruktoptas** [faruktoptas/FancyShowCaseView#9]

**Comment by daboome** [comment]
Do you imply that robolecric unit test should be added to sample application?

**Comment by faruktoptas** [comment]
It should be in library not sample.

**Comment by faruktoptas** [comment]
You can check this: https://github.com/sjwall/MaterialTapTargetPrompt/blob/master/library/src/test/java/uk/co/samuelwall/materialtaptargetprompt/MaterialTapTargetPromptUnitTest.java

**Comment by daboome** [comment]
I took a look on the related library you provided. All fields of that library are made package local, so that the library code is testable within library package. Should I do the same (i.e. changing all private fields to package local) for the sake of testing?

**Comment by faruktoptas** [comment]
Sure. Tests may be in the same module.

**Comment by faruktoptas** [comment]
Espresso tests will be used.
