### ISSUE TITLE
Focus not centered at the actionbar item

### ISSUE THREAD

**Issue by harshvardhan-takawale** [faruktoptas/FancyShowCaseView#91]
I am trying to use the fancyshowcase view on an actionbar item but it is off-centered. Can something be done?
![screenshot_20180217-184951](https://user-images.githubusercontent.com/28982436/36341431-3a943788-1414-11e8-9425-44579a42cb16.png)

**Comment by faruktoptas** [comment]
Your root view has android:fitSystemWindiws="true"?

**Comment by faruktoptas** [comment]
`.fitSystemWindows(true)` MUST be added to builder parameters if your root view has `android:fitsSystemWindows="true"`

**Comment by harshvardhan-takawale** [comment]
It worked. Thankyou so much sir

**Comment by harshvardhan-takawale** [comment]
@faruktoptas Can we point to the three dots in the action bar that are there to open the menu?

**Comment by faruktoptas** [comment]
@harshvardhan-takawale If you use a theme with ActionBar you need to get the view reference of ActionBar then find the child view.
I think you should use Toolbar. It would be easier with `toolBar.getChildAt(index)`

**Comment by kapilb145** [comment]
> .fitSystemWindows(true)

thanks its work perfectly
