### ISSUE TITLE
Revealed section does not fit view

### ISSUE THREAD

**Issue by DavidEdwards** [faruktoptas/FancyShowCaseView#93]
In my App, the pulsated revealed section is too high. 

Here is an example screenshot showing the positions. The red arrows indicate which view it is supposed to be highlighting.

![image](https://user-images.githubusercontent.com/1585923/36938632-9abaf104-1f24-11e8-9d21-82ec00b2d55d.png)

Is this a known issue? Perhaps a resolution?

**Comment by DavidEdwards** [comment]
For what it is worth, I added a margin to the top of the view. It resolves my issue. Perhaps a margin could be built into the API?

```
FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,
        ViewGroup.LayoutParams.MATCH_PARENT);

float density = getResources().getDisplayMetrics().density;
params.topMargin = (int) (24 * density);
```

**Comment by faruktoptas** [comment]
.fitSystemWindows(true) MUST be added to builder parameters if your root view has android:fitsSystemWindows="true"

**Comment by DavidEdwards** [comment]
Ah ha. That did it. Thank you for the update.

May I suggest adding that to the wiki? That is an invaluable bit of information.

Great library by the way, thank you for releasing it. This will make my Apps on-boarding process much easier.

I'll be adding it to this App: https://play.google.com/store/apps/details?id=dae.notificationreader

**Comment by faruktoptas** [comment]
You can see it on the wiki :)
I think I should move it to README.md.

**Comment by DavidEdwards** [comment]
Wow. On the first page. I don't know how I missed it.

Double apologies.
