### ISSUE TITLE
Title text is not multiline

### ISSUE THREAD

**Issue by ankursharma234** [faruktoptas/FancyShowCaseView#95]
If the title is too big, the title show .... at the end of the line. It doesnt show in next line

**Comment by faruktoptas** [comment]
Thanks @ankursharma234 
You can send a PR to fix it. Or you can use custom views as a workaround https://github.com/faruktoptas/FancyShowCaseView/wiki/3.-Inflate-Custom-View

**Comment by faruktoptas** [comment]
Title is multiline. Example: https://github.com/faruktoptas/FancyShowCaseView/blob/b6a102b926e3810a887be5b05da2b9ec9d223991/app/src/main/java/me/toptas/fancyshowcasesample/MainActivity.kt#L106
