### ISSUE TITLE
Flag to set Title above or below the view

### ISSUE THREAD

**Issue by JDSCaram** [faruktoptas/FancyShowCaseView#99]
Hello, it is possible?
Flag to set Title above or below the view with focus.
I know that is possible using .titleStyle or titleGravity to set the position for label
However when the view is in the center of the screen and I put 
`Gravity.CENTER_HORIZONTAL | Gravity.TOP`
the title is too far from the view depending on the size of the screen.
I do not want to have customization layouts just to display a title.

**Comment by faruktoptas** [comment]
Hello @JDSCaram 
For now, you can do it with custom layouts. But there is a PR (#43 ) for automatic text positioning. But I think it is inactive now. It has a small issue with `focusCircleRadiusFactor` parameter. I will add this feature asap. 
You can send PR if you are interested in contributing this library.

**Comment by krupinder955** [comment]
Can we set the custom view below the focused view ?

**Comment by faruktoptas** [comment]
@krupinder955 no not only below the focused view. You can set custom view for the whole view.

**Comment by faruktoptas** [comment]
Auto position feature is added with https://github.com/faruktoptas/FancyShowCaseView/commit/747ae80f8754065f33858b8c2d5dd1392f075ddb
